var bookChoice={getType:function(){if(browser.platform.ios)if(orientationObserver.getOrientation()==="landscape")return device.name()=="iPad"?"two":"one";else{orientationObserver.getOrientation();return"one"}else return browser.platform.android||browser.platform.wphone?browser.publisher.name=="Publisher2"?"two":"one":"two"}};if(typeof XML=="undefined")XML=function(){};XML.ObjTree=function(){return this};XML.ObjTree.VERSION="0.24";XML.ObjTree.prototype.xmlDecl='<?xml version="1.0" encoding="UTF-8" ?>\n';
XML.ObjTree.prototype.attr_prefix="-";XML.ObjTree.prototype.overrideMimeType="text/xml";XML.ObjTree.prototype.parseXML=function(a){var b;if(window.DOMParser){b=new DOMParser;a=b.parseFromString(a,"application/xml");if(!a)return;b=a.documentElement}else if(window.ActiveXObject){b=new ActiveXObject("Microsoft.XMLDOM");b.async=false;b.loadXML(a);b=b.documentElement}if(b)return this.parseDOM(b)};
XML.ObjTree.prototype.parseHTTP=function(a,b,c){var d={},e;for(e in b)d[e]=b[e];if(!d.method)d.method=typeof d.postBody=="undefined"&&typeof d.postbody=="undefined"&&typeof d.parameters=="undefined"?"get":"post";if(c){d.asynchronous=true;var h=this,g=d.onComplete;d.onComplete=function(j){var k;if(j&&j.responseXML&&j.responseXML.documentElement)k=h.parseDOM(j.responseXML.documentElement);else if(j&&j.responseText)k=h.parseXML(j.responseText);c(k,j);g&&g(j)}}else d.asynchronous=false;var f;if(typeof HTTP!=
"undefined"&&HTTP.Request){d.uri=a;if(a=new HTTP.Request(d))f=a.transport}else if(typeof Ajax!="undefined"&&Ajax.Request)if(a=new Ajax.Request(a,d))f=a.transport;if(c)return f;if(f&&f.responseXML&&f.responseXML.documentElement)return this.parseDOM(f.responseXML.documentElement);else if(f&&f.responseText)return this.parseXML(f.responseText)};
XML.ObjTree.prototype.parseDOM=function(a){if(a){this.__force_array={};if(this.force_array)for(var b=0;b<this.force_array.length;b++)this.__force_array[this.force_array[b]]=1;b=this.parseElement(a);if(this.__force_array[a.nodeName])b=[b];if(a.nodeType!=11){var c={};c[a.nodeName]=b;b=c}return b}};
XML.ObjTree.prototype.parseElement=function(a){if(a.nodeType!=7){if(a.nodeType==3||a.nodeType==4){if(a.nodeValue.match(/[^\x00-\x20]/)==null)return;return a.nodeValue}var b,c={};if(a.attributes&&a.attributes.length){b={};for(var d=0;d<a.attributes.length;d++){var e=a.attributes[d].nodeName;if(typeof e=="string"){var h=a.attributes[d].nodeValue;if(h){e=this.attr_prefix+e;if(typeof c[e]=="undefined")c[e]=0;c[e]++;this.addNode(b,e,c[e],h)}}}}if(a.childNodes&&a.childNodes.length){e=true;if(b)e=false;
for(d=0;d<a.childNodes.length&&e;d++){h=a.childNodes[d].nodeType;h==3||h==4||(e=false)}if(e){b||(b="");for(d=0;d<a.childNodes.length;d++)b+=a.childNodes[d].nodeValue}else{b||(b={});for(d=0;d<a.childNodes.length;d++){e=a.childNodes[d].nodeName;if(typeof e=="string")if(h=this.parseElement(a.childNodes[d])){if(typeof c[e]=="undefined")c[e]=0;c[e]++;this.addNode(b,e,c[e],h)}}}}return b}};
XML.ObjTree.prototype.addNode=function(a,b,c,d){if(this.__force_array[b]){if(c==1)a[b]=[];a[b][a[b].length]=d}else if(c==1)a[b]=d;else if(c==2)a[b]=[a[b],d];else a[b][a[b].length]=d};XML.ObjTree.prototype.writeXML=function(a){return this.xmlDecl+this.hash_to_xml(null,a)};
XML.ObjTree.prototype.hash_to_xml=function(a,b){var c=[],d=[],e;for(e in b)if(b.hasOwnProperty(e)){var h=b[e];if(e.charAt(0)!=this.attr_prefix)c[c.length]=typeof h=="undefined"||h==null?"<"+e+" />":typeof h=="object"&&h.constructor==Array?this.array_to_xml(e,h):typeof h=="object"?this.hash_to_xml(e,h):this.scalar_to_xml(e,h);else d[d.length]=" "+e.substring(1)+'="'+this.xml_escape(h)+'"'}d=d.join("");e=c.join("");typeof a=="undefined"||a==null||(e=c.length>0?e.match(/\n/)?"<"+a+d+">\n"+e+"</"+a+">\n":
"<"+a+d+">"+e+"</"+a+">\n":"<"+a+d+" />\n");return e};XML.ObjTree.prototype.array_to_xml=function(a,b){for(var c=[],d=0;d<b.length;d++){var e=b[d];c[c.length]=typeof e=="undefined"||e==null?"<"+a+" />":typeof e=="object"&&e.constructor==Array?this.array_to_xml(a,e):typeof e=="object"?this.hash_to_xml(a,e):this.scalar_to_xml(a,e)}return c.join("")};XML.ObjTree.prototype.scalar_to_xml=function(a,b){return a=="#text"?this.xml_escape(b):"<"+a+">"+this.xml_escape(b)+"</"+a+">\n"};
XML.ObjTree.prototype.xml_escape=function(a){return String(a).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;")};
var bookData={loaded:false,background:"",load:function(a){function b(e){var h={},g,f=1;if(e.length)for(g in e){g=e[g];h[f]={};if(g.title)h[f].name=g.title["@value"];if(g.pageNumber)h[f].page=g.pageNumber["@value"];if(g.children){h[f].children={};h[f].children.tocElement=b(g.children.tocData)}f++}else{h[1]={};if(e.title)h[1].name=e.title["@value"];if(e.pageNumber)h[1].page=e.pageNumber["@value"];if(e.children){h[1].children={};h[1].children.tocElement=b(e.children.tocData)}}return h}var c=new XML.ObjTree;
c.attr_prefix="@";a=c.parseDOM(a);a=a["#document"];this.size={};this.size.width=a.Properties.bookProperties.bookWidth?a.Properties.bookProperties.bookWidth["@value"]:600;this.size.height=a.Properties.bookProperties.bookHeight?a.Properties.bookProperties.bookHeight["@value"]:800;bookData.background=a.Properties.bookProperties.bookBG["@src"];bookData.TOC={};if(a.Properties.tableOfContent.tocData.children){bookData.TOC.tocElement={};bookData.TOC.tocElement=b(a.Properties.tableOfContent.tocData.children.tocData)}this.page=
{};c=0;for(itemNum in a.Properties.bookProperties.pages.elements.page){c++;if(itemNum==="id"){var d=a.Properties.bookProperties.pages.elements.page[itemNum];itemNum=null;itemNum={};itemNum.id={};itemNum.id["@value"]=d["@value"];d=null}else itemNum=a.Properties.bookProperties.pages.elements.page[itemNum];bookData.page[c]={};bookData.page[c].width=itemNum.width?itemNum.isWide&&itemNum.isWide["@value"]=="true"?itemNum.width["@value"]/2:itemNum.width["@value"]:itemNum.isWide&&itemNum.isWide["@value"]==
"true"?a.Properties.bookProperties.pages.defaultValue.width["@value"]/2:a.Properties.bookProperties.pages.defaultValue.width["@value"];bookData.page[c].height=itemNum.height?itemNum.height["@value"]:a.Properties.bookProperties.pages.defaultValue.height["@value"];bookData.page[c].proportions=(bookData.page[c].width/bookData.page[c].height-0.0010).toFixed(2);bookData.page[c].stub=itemNum.isStub?true:false;if(itemNum.isWide&&itemNum.isWide["@value"]=="true"){bookData.page[c+1]={};bookData.page[c+1].height=
bookData.page[c].height;bookData.page[c+1].width=bookData.page[c].width;bookData.page[c+1].stub=bookData.page[c].stub;bookData.page[c+1].proportions=bookData.page[c].proportions;bookData.page[c].wide=true;bookData.page[c+1].wide=true;bookData.page[c].src=images.getImagePath(itemNum.id["@value"],"stand",true,1);bookData.page[c+1].src=images.getImagePath(itemNum.id["@value"],"stand",true,2);bookData.page[c].srcZoom=images.getImagePath(itemNum.id["@value"],"zoom",true,1);bookData.page[c+1].srcZoom=images.getImagePath(itemNum.id["@value"],
"zoom",true,2);if(itemNum.links){bookData.page[c].links={};this.linksImport(itemNum,c)}c++}else{bookData.page[c].src=images.getImagePath(itemNum.id["@value"]);bookData.page[c].srcZoom=images.getImagePath(itemNum.id["@value"],"zoom");bookData.page[c].wide=false;if(itemNum.links){bookData.page[c].links={};this.linksImport(itemNum,c)}}}this.pageCount=c;c=null;this.size.proportions=(bookData.size.width/bookData.size.height-0.0010).toFixed(2);this.loaded=true},linksImport:function(a,b,c){c=c||"normal";
a=a.links.link[0]?a.links.link:[a.links.link];for(var d=0;d<a.length;d++){bookData.page[b].links[d]=[];if(c=="wide"){bookData.page[b+1].links[d]=[];if(a[d].x["@value"]*1>bookData.size.width*1){bookData.page[b+1].links[d].x=a[d].x["@value"]-bookData.size.width*1;bookData.page[b].links[d].width=a[d].width["@value"]}else if(a[d].x["@value"]*1<bookData.size.width*1&&a[d].x["@value"]*1+a[d].width["@value"]*1>bookData.size.width*1){bookData.page[b].links[d].x=a[d].x["@value"];bookData.page[b+1].links[d].x=
0;bookData.page[b].links[d].width=a[d].width["@value"]*1-a[d].x["@value"]*1;bookData.page[b+1].links[d].width=a[d].x["@value"]*1+a[d].width["@value"]*1-bookData.size.width*1}else{bookData.page[b].links[d].x=a[d].x["@value"];bookData.page[b].links[d].width=a[d].width["@value"]}bookData.page[b].links[d].y=a[d].y["@value"]}else{bookData.page[b].links[d].x=a[d].x["@value"];bookData.page[b].links[d].y=a[d].y["@value"];bookData.page[b].links[d].width=a[d].width["@value"]}bookData.page[b].links[d].height=
a[d].height["@value"];if(a[d].page["@id"])bookData.page[b].links[d].page=a[d].page["@id"];if(a[d].urls){bookData.page[b].links[d].urls=[];if(a[d].urls.url[0])for(var e=0;e<a[d].urls.url.length;e++)bookData.page[b].links[d].urls[e]=a[d].urls.url[e].src;else bookData.page[b].links[d].urls[0]=a[d].urls.url["@src"]}}}},browser={name:"",version:"",platform:"",detect:function(){var a=navigator.userAgent.toLowerCase(),b=navigator.platform.toLowerCase(),c=a.match(/(opera|ie|firefox|chrome|version)[\s\/:]([\w\d\.]+)?.*?(safari|version[\s\/:]([\w\d\.]+)|$)/)||
[null,"unknown",0];mode=c[1]=="ie"&&document.documentMode;browser.name=c[1]=="version"?c[3]:c[1];if(browser.name==="opera")crossHTML5.prefix="-o-";else if(browser.name==="safari")crossHTML5.prefix="-webkit-";else if(browser.name==="firefox")crossHTML5.prefix="-moz-";else if(browser.name==="ie")crossHTML5.prefix="-ms-";browser.version=mode||parseFloat(c[1]=="opera"&&c[4]?c[4]:c[2]);browser.platform={name:a.match(/ip(?:ad|od|hone)/)?"ios":a.match(/(?:msie 9)/)?"wphone":(a.match(/(?:webos|android|bada|symbian|palm|blackberry)/)||
b.match(/mac|win|linux/)||["other"])[0]};browser.publisher={name:a.match(/(?:preview_publisher_2)/)?"Publisher2":(a.match(/(?:publisher_3|publisher)/)||["other"])[0]};browser[browser.name]=true;browser[browser.name+parseInt(browser.version,10)]=true;browser.platform[browser.platform.name]=true;if(browser.platform.android){a=document.createElement("meta");a.name="viewport";a.content="user-scalable=0; ";document.getElementsByTagName("head")[0].appendChild(a)}}},crossHTML5={prefix:"",perspective:function(a,
b){a.style[this.prefix+"perspective"]=b},backfaceVisibility:function(a,b){a.style[this.prefix+"backface-visibility"]=b},boxShadow:function(a,b){a.style[this.prefix+"box-shadow"]=b},transitionDuration:function(a,b){a.style[this.prefix+"transition-duration"]=b},transform:function(a,b,c){b=b||false;c=c||false;if(!b&&!c)return a.style[this.prefix+"transform"];else a.style[this.prefix+"transform"]=this.prefix==="-webkit-"?b:c}},device={width:function(){if(browser)return browser.publisher?browser.publisher.name===
"publisher"?window.innerWidth*2:window.innerWidth:window.innerWidth},height:function(){return this.name()=="iPhone3G"||this.name()=="iPhone4G"?window.innerHeight==416&&orientationObserver.getOrientation()=="portrait"?window.innerHeight:window.innerHeight<416&&orientationObserver.getOrientation()=="portrait"?window.innerHeight+60:window.innerHeight>250&&orientationObserver.getOrientation()=="landscape"?window.innerHeight:window.innerHeight<250&&orientationObserver.getOrientation()=="landscape"?window.innerHeight+
60:window.innerHeight:browser.publisher.name==="publisher"?window.innerHeight*2:window.innerHeight},proportions:function(){return(this.width()/this.height()).toFixed(2)},name:function(){var a;a=window.innerWidth<=480&&browser.platform.ios&&orientationObserver.getOrientation()=="landscape"?"iPhone3G":"other";a=window.innerWidth<=320&&browser.platform.ios&&orientationObserver.getOrientation()=="portrait"?"iPhone3G":a;a=window.innerWidth<=960&&window.innerWidth>480&&browser.platform.ios&&orientationObserver.getOrientation()==
"landscape"?"iPhone4G":a;a=window.innerWidth<=640&&window.innerWidth>320&&browser.platform.ios&&orientationObserver.getOrientation()=="portrait"?"iPhone4G":a;a=window.innerWidth<=1024&&window.innerWidth>960&&browser.platform.ios&&orientationObserver.getOrientation()=="landscape"?"iPad":a;a=window.innerWidth<=768&&window.innerWidth>640&&browser.platform.ios&&orientationObserver.getOrientation()=="portrait"?"iPad":a;a=browser.platform.android==true?"android":a;return a=browser.platform.wphone==true?
"wphone":a}},eventManager={touchInterface:false,leftAndRightArea:0.15,gesture:false,touchStartCoordinate:{x:0,y:0},clickStartCoordinate:{x:0,y:0},click:false,clickCount:0,doubleClickTime:250,start:function(){if("createTouch"in document){eventManager.touchInterface=true;eventManager.loadTouchEvents()}else{eventManager.touchInterface=false;eventManager.loadClickEvents()}},loadTouchEvents:function(){var a=document.getElementById("mainFrame"),b=function(f){f.target=f.target?f.target:f.srcElement;f.preventDefault?
f.preventDefault():f.returnValue=false;eventManager.gesture=true;delete b},c=function(f){f.target=f.target?f.target:f.srcElement;f.preventDefault?f.preventDefault():f.returnValue=false;delete c},d=function(f){f.target=f.target?f.target:f.srcElement;f.preventDefault?f.preventDefault():f.returnValue=false;window.setTimeout(function(){eventManager.gesture=false},10);delete d};a.addEventListener("gesturestart",b,false);a.addEventListener("gesturechange",c,false);a.addEventListener("gestureend",d,false);
var e=function(f){f.target=f.target?f.target:f.srcElement;pager.state=="input"&&pager.cancelInput();eventManager.touchStartCoordinate.x=f.targetTouches[0].pageX;eventManager.touchStartCoordinate.y=f.targetTouches[0].pageY;if(twoPageBook.installed&&!zoomBook.installed)twoPageBook.events.touchStart(f);else if(onePageBook.installed&&!zoomBook.installed)onePageBook.events.touchStart(f);else zoomBook.installed&&zoomBook.events.touchStart(f);f.preventDefault?f.preventDefault():f.returnValue=false;delete e},
h=function(f){f.target=f.target?f.target:f.srcElement;if(twoPageBook.installed&&!zoomBook.installed)twoPageBook.events.touchMove(f);else if(onePageBook.installed&&!zoomBook.installed)onePageBook.events.touchMove(f);else zoomBook.installed&&zoomBook.events.touchMove(f);f.preventDefault?f.preventDefault():f.returnValue=false;delete h},g=function(f){f.target=f.target?f.target:f.srcElement;if(twoPageBook.installed&&!zoomBook.installed)twoPageBook.events.touchEnd(f);else if(onePageBook.installed&&!zoomBook.installed)onePageBook.events.touchEnd(f);
else zoomBook.installed&&zoomBook.events.touchEnd(f);f.preventDefault?f.preventDefault():f.returnValue=false;delete g};a.addEventListener("touchstart",e,false);a.addEventListener("touchmove",h,false);a.addEventListener("touchend",g,false);delete null},loadClickEvents:function(){var a=function(e){e.target=e.target?e.target:e.srcElement;e.preventDefault?e.preventDefault():e.returnValue=false;eventManager.click=true;pager.state=="input"&&pager.cancelInput();eventManager.clickStartCoordinate.x=e.pageX;
eventManager.clickStartCoordinate.y=e.pageY;if(twoPageBook.installed&&!zoomBook.installed)twoPageBook.events.mousedown(e);else if(onePageBook.installed&&!zoomBook.installed)onePageBook.events.mousedown(e);else zoomBook.installed&&zoomBook.events.mousedown(e);delete a},b=function(e){e.target=e.target?e.target:e.srcElement;e.preventDefault?e.preventDefault():e.returnValue=false;eventManager.click=false;if(twoPageBook.installed&&!zoomBook.installed)twoPageBook.events.mouseup(e);else if(onePageBook.installed&&
!zoomBook.installed)onePageBook.events.mouseup(e);else zoomBook.installed&&zoomBook.events.mouseup(e);delete b},c=function(e){e.target=e.target?e.target:e.srcElement;e.preventDefault?e.preventDefault():e.returnValue=false;if(eventManager.click)if(twoPageBook.installed&&!zoomBook.installed)twoPageBook.events.mousemove(e);else if(onePageBook.installed&&!zoomBook.installed)onePageBook.events.mousemove(e);else zoomBook.installed&&zoomBook.events.mousemove(e);delete c},d=document.getElementById("mainFrame");
d.addEventListener("mousedown",a,false);d.addEventListener("mousemove",c,false);d.addEventListener("mouseup",b,false);delete null},pagerEvent:function(){document.getElementById("pagerCurrentPage").addEventListener("click",pager.enableInput,false)},pagerInputEvent:function(){if(pager.installed&&pager.state=="input"){var a=function(b){b.target=b.target?b.target:b.srcElement;if(b.keyCode==13){pager.change();pageMediator.goToPage(b.target.value)}delete a};document.getElementById("inputPage").addEventListener("keydown",
a,false)}},linkClick:function(a,b,c,d){if(eventManager.touchInterface)var e=a.changedTouches[0].pageX-a.target.getBoundingClientRect().left,h=a.changedTouches[0].pageY-a.target.getBoundingClientRect().top;else{e=a.clientX-a.target.getBoundingClientRect().left;h=a.clientY-a.target.getBoundingClientRect().top}for(linkI in bookData.page[b].links){var g=bookData.page[b].links[linkI];if(e>=g.x*c&&e<=g.x*c+g.width*c&&h>=(g.y*d).toFixed(0)*1&&h<=((g.y*d).toFixed(0)*1+g.height*d).toFixed(0)*1){a.preventDefault?
a.preventDefault():a.returnValue=false;a.stopPropagation?a.stopPropagation():a.cancelBubble=true;var f=g.x*c,j=g.y*d;if(eventManager.touchInterface){var k=a.target.getContext("2d"),o=k.getImageData(f,j,g.width*c+10,g.height*d+10);k.fillStyle="rgba(0,0,0,0.4)";k.fillRect(g.x*c,g.y*d,g.width*c,g.height*d);(function(l){a.target.addEventListener("touchend",function(){k.putImageData(o,f,j);l.page&&pageMediator.goToPage(l.page);if(l.urls)for(var m=0;m<l.urls.length;m++)window.open(l.urls[m])})})(g)}else{g.page&&
pageMediator.goToPage(g.page);if(g.urls)for(var n=0;n<g.urls.length;n++)window.open(g.urls[n])}}}}},images={image:new Image,imageStack:[],processing:false,getImagePath:function(a,b,c,d){c=c||false;d=d||0;var e="000"+a;if(a>9)e="00"+a;if(a>99)e="0"+a;if(a>999)e=""+a;if(dir==null)PATH_TO_PROPERTIES=photographer_img;if((b||"")==="zoom")return c?PATH_TO_PROPERTIES+"page"+e+"_i2_"+d+".jpg?id="+Math.random().toFixed(5)*1E5:PATH_TO_PROPERTIES+"page"+e+"_i2.jpg?id="+Math.random().toFixed(5)*1E5;if(device.name()==
"iPhone3G")return c?PATH_TO_PROPERTIES+"page"+e+"_i1_"+d+".jpg?id="+Math.random().toFixed(5)*1E5:PATH_TO_PROPERTIES+"page"+e+"_i1.jpg?id="+Math.random().toFixed(5)*1E5;if(device.name()=="iPhone4G")return c?PATH_TO_PROPERTIES+"page"+e+"_i1_"+d+".jpg?id="+Math.random().toFixed(5)*1E5:PATH_TO_PROPERTIES+"page"+e+"_i1.jpg?id="+Math.random().toFixed(5)*1E5;if(device.name()=="iPad")return c?PATH_TO_PROPERTIES+"page"+e+"_i1_"+d+".jpg?id="+Math.random().toFixed(5)*1E5:PATH_TO_PROPERTIES+"page"+e+"_i1.jpg?id="+
Math.random().toFixed(5)*1E5;if(device.name()=="android"||device.name()=="wphone")return c?PATH_TO_PROPERTIES+"page"+e+"_i1_"+d+".jpg?id="+Math.random().toFixed(5)*1E5:PATH_TO_PROPERTIES+"page"+e+"_i1.jpg?id="+Math.random().toFixed(5)*1E5;if(device.name()=="other")return c?PATH_TO_PROPERTIES+"page"+e+"_i2_"+d+".jpg?id="+Math.random().toFixed(5)*1E5:PATH_TO_PROPERTIES+"page"+e+"_i2.jpg?id="+Math.random().toFixed(5)*1E5},init:function(){this.image.onload=this.loadImage},loadImage:function(){var a=this.id;
if(el.id("canvas"+a)){preloader.deletePreloader(a*1);var b=el.id("canvas"+a).getContext("2d");if(twoPageBook.installed&&!zoomBook.installed)var c=twoPageBook.bookWidth/2,d=twoPageBook.bookHeight;else if(onePageBook.installed&&!zoomBook.installed){c=onePageBook.bookWidth;d=onePageBook.bookHeight}else if(zoomBook.installed){c=zoomBook.pageWidth;d=zoomBook.pageHeight}if(bookData.page[a].proportions>=bookData.size.proportions){var e=c,h=(e/bookData.page[a].proportions).toFixed(0);c=(d-h)/2}else{h=d;e=
(h*bookData.page[a].proportions).toFixed(0);c=bookData.page[a].wide&&a%2==0?c-e:0}bookData.page[a].proportions>=bookData.size.proportions?b.drawImage(images.image,0,c,e,h):b.drawImage(images.image,c,0,e,h);if(a!=1&&a!=bookData.pageCount&&twoPageBook.installed)images.drawShadow(b,a);else a==bookData.pageCount&&a%2!=0&&images.drawShadow(b,a)}if(images.imageStack.length>0)images.shiftImage();else images.processing=false},drawShadow:function(a,b){if(b%2==0){var c=a.createLinearGradient(twoPageBook.bookWidth/
2-twoPageBook.bookWidth/10,0,twoPageBook.bookWidth/2,0);c.addColorStop(0,"rgba(0,0,0,0.0)");c.addColorStop(0.4,"rgba(0,0,0,0.05)");c.addColorStop(0.8,"rgba(0,0,0,0.20)");c.addColorStop(1,"rgba(0,0,0,0.15)")}else{c=a.createLinearGradient(twoPageBook.bookWidth/20,0,0,0);c.addColorStop(0,"rgba(0,0,0,0)");c.addColorStop(0.6,"rgba(0,0,0,0.1)");c.addColorStop(0.95,"rgba(0,0,0,0.2)");c.addColorStop(1,"rgba(0,0,0,0.65)")}a.fillStyle=c;if(b%2==0){a.fillRect(twoPageBook.bookWidth/2-twoPageBook.bookWidth/4,
0,twoPageBook.bookWidth/4,twoPageBook.bookHeight);a.beginPath();a.moveTo(twoPageBook.bookWidth/2,0);a.lineTo(twoPageBook.bookWidth/2,twoPageBook.bookHeight);a.strokeStyle="rgba(0,0,0,0.1)";a.stroke()}else a.fillRect(0,0,twoPageBook.bookWidth/10,twoPageBook.bookHeight)},shiftImage:function(){if(this.imageStack.length>0){this.processing=true;var a=this.imageStack.shift();this.image.id=a;this.image.src=zoomBook.installed?bookData.page[a].srcZoom+Math.random().toFixed(5)*1E5:bookData.page[a].src+Math.random().toFixed(5)*
1E5}},push:function(a){this.imageStack.push(a);this.processing||this.shiftImage()},deleteImageFromStack:function(a){a=images.imageStack.indexOf(a);a!=-1&&images.imageStack.splice(a,1)}},links={currStorage:"",currCanvas:"",currX:0,currY:0,currGoPage:0,isLinkBool:false,currURLs:0,drawRect:function(a){links.clearRect();if(onePageBook.installed)var b=onePageBook.currentPage;else if(twoPageBook.installed)if(a.target.id=="canvas"+twoPageBook.currentPage.left)b=twoPageBook.currentPage.left;else{if(a.target.id==
"canvas"+twoPageBook.currentPage.right)b=twoPageBook.currentPage.right}else if(zoomBook.installed)b=zoomBook.currentPage;var c=a.target.width/bookData.size.width,d=a.target.height/bookData.size.height;if(eventManager.touchInterface)var e=eventManager.touchStartCoordinate.x-a.target.getBoundingClientRect().left,h=eventManager.touchStartCoordinate.y-a.target.getBoundingClientRect().top;else{e=a.clientX-a.target.getBoundingClientRect().left;h=a.clientY-a.target.getBoundingClientRect().top}if(bookData.page[b])for(linkI in bookData.page[b].links){var g=
bookData.page[b].links[linkI];links.isLinkBool=false;if(e>=g.x*c&&e<=g.x*c+g.width*c&&h>=(g.y*d).toFixed(0)*1&&h<=((g.y*d).toFixed(0)*1+g.height*d).toFixed(0)*1){links.currX=g.x*c;links.currY=g.y*d;b=a.target.getContext("2d");links.currCanvas=a.target.id;links.currStorage=b.getImageData(links.currX,links.currY,g.width*c+10,g.height*d+10);b.fillStyle="rgba(0,0,0,0.3)";b.fillRect(g.x*c,g.y*d,g.width*c,g.height*d);links.currGoPage=g.page?g.page:0;links.currURLs=g.urls?g.urls:0;links.isLinkBool=true;
break}}},clearRect:function(){if(el.id(links.currCanvas)){el.id(links.currCanvas).getContext("2d").putImageData(links.currStorage,links.currX,links.currY);links.isLinkBool=false}}};
document.addEventListener("DOMContentLoaded",function(){function a(d){bookChoice.getType()==="one"?onePageBook.draw(d):twoPageBook.draw(d);if(browser.publisher.name==="publisher"){el.id("scaler").style.position="absolute";el.id("scaler").style.overflow="hidden";el.id("scaler").style.width=window.innerWidth+"px";el.id("scaler").style.height=window.innerHeight+"px";el.id("body").style.webkitTransform="scale(0.5) translate(-"+device.width()/2+"px,-"+device.height()/2+"px)"}window.addEventListener("beforeunload",
function(){console.log("pop")},false)}if(dir=="./<%=FilesFolderName%>/")dir="files";PATH_TO_PROPERTIES="../"+assetsFolder+"/mobile/";if(dir==null){PATH_TO_PROPERTIES=photographer_dir;STYLES_SRC=photographer_src}var b=function(){browser.detect();preloader.init();bookData.load(this.responseXML);images.init();workspace.draw();toolbar.draw();toc.init();pager.draw();orientationObserver.start();eventManager.start();if(window.location.hash){var d=window.location.hash.substring(1,window.location.hash.length);
d=parseInt(d);if(d<=0)d=1;else if(d>bookData.pageCount)d=bookData.pageCount;a(d);d=null}else a(1);if(bookData.background!="image/grey-inner.jpg"&&bookData.background!="image/grey-outer.jpg"&&bookData.background!="image/dark-wood-inner.jpg"&&bookData.background!="image/dark-wood-outer.jpg"&&bookData.background!="image/sky-blue-inner.jpg"&&bookData.background!="image/sky-blue-outer.jpg"){el.id("body").style.backgroundImage="url(../"+assetsFolder+"/"+bookData.background+")";el.id("mainFrame").style.backgroundImage=
"url(../"+assetsFolder+"/"+bookData.background+")"}window.setTimeout(function(){window.scrollTo(0,1)},10);delete b},c=new XMLHttpRequest;c.open("GET",PATH_TO_PROPERTIES+"properties.xml");c.onload=b;c.send();delete c},false);
var el={id:function(a){return document.getElementById(a)},tag:function(a){return document.getElementsByTagName(a)[0]},tags:function(a){return document.getElementsByTagName(a)},add:function(a){return document.createElement(a)},del:function(a){el.id(a).parentNode.removeChild(el.id(a))},Class:function(){return document.getElementsByClassName(tag)}},onePageBook={currentPage:0,installed:false,nextPageBuffer:2,prevPageBuffer:2,flipSpeed:600,triggerStopTime:700,bookWidth:0,bookHeight:0,bookTop:0,bookLeft:0,
draw:function(a){if(bookData.size.proportions<device.proportions()){onePageBook.bookHeight=(device.height()-50).toFixed(0);onePageBook.bookWidth=(onePageBook.bookHeight*bookData.size.proportions).toFixed(0)}else{onePageBook.bookWidth=device.width()-50;onePageBook.bookHeight=(onePageBook.bookWidth/bookData.size.proportions).toFixed(0)}onePageBook.bookTop=((device.height()-onePageBook.bookHeight)/2).toFixed(0);onePageBook.bookLeft=((device.width()-onePageBook.bookWidth)/2).toFixed(0);if(el.id("bookPortrait"))el.id("bookPortrait");
else{var b=el.add("div");b.id="bookPortrait";crossHTML5.perspective(b,"3000");b.style.position="absolute";b.style.width=onePageBook.bookWidth+"px";b.style.height=onePageBook.bookHeight+"px";b.style.top=onePageBook.bookTop+"px";b.style.left=onePageBook.bookLeft+"px";b.style.zIndex="2";crossHTML5.backfaceVisibility(b,"hidden");crossHTML5.boxShadow(b,"0px 0px 3px #000");el.id("mainFrame").appendChild(b)}onePageBook.installed=true;onePageBook.currentPage=a;pager.change();for(b=a-onePageBook.prevPageBuffer;b<=
a*1+onePageBook.nextPageBuffer;b++)onePageBook.drawPage(b)},drawPage:function(a){if(a>0&&a<=bookData.pageCount&&!el.id("canvas"+a)){var b=el.add("canvas");b.id="canvas"+a;b.className="canvasBook";b.width=onePageBook.bookWidth;b.height=onePageBook.bookHeight;b.style.position="absolute";b.style.left=a<onePageBook.currentPage?-device.width()+"px":"";b.style.zIndex=bookData.pageCount-a+"";var c=b.getContext("2d");c.fillStyle="rgb(255,255,255)";c.fillRect(0,0,onePageBook.bookWidth,onePageBook.bookHeight);
el.id("bookPortrait").appendChild(b);if(!bookData.page[a].stub){images.push(a);preloader.add(a)}}},destroyPage:function(a){el.id("canvas"+a)&&el.del("canvas"+a);preloader.deletePreloader(a)},next:function(){if(onePageBook.installed&&onePageBook.currentPage<bookData.pageCount&&timer.check("fx")){onePageBook.slideFxPage(onePageBook.currentPage);if(el.id("bookPortrait").childNodes.length==5){var a=onePageBook.currentPage-onePageBook.prevPageBuffer;images.deleteImageFromStack(a);onePageBook.destroyPage(a);
preloader.deletePreloader(a);window.scrollTo(0,1)}onePageBook.currentPage++;onePageBook.drawPage(onePageBook.currentPage*1+onePageBook.nextPageBuffer*1);pager.change();timer.setBlockTime(twoPageBook.flipSpeed/2,twoPageBook.flipSpeed)}toc.tocLock||toc.hide()},prev:function(){if(onePageBook.installed&&onePageBook.currentPage>1&&timer.check("fx")){onePageBook.slideFxPage(onePageBook.currentPage-1);if(el.id("bookPortrait").childNodes.length==5){var a=onePageBook.currentPage*1+onePageBook.nextPageBuffer*
1;images.deleteImageFromStack(a);onePageBook.destroyPage(a);window.scrollTo(0,1)}onePageBook.currentPage--;onePageBook.drawPage(onePageBook.currentPage-onePageBook.prevPageBuffer);pager.change();timer.setBlockTime(twoPageBook.flipSpeed/2,twoPageBook.flipSpeed)}toc.tocLock||toc.hide()},slideFxPage:function(a){if(a<onePageBook.currentPage)var b=onePageBook.bookLeft*2+onePageBook.bookWidth*1;else if(a==onePageBook.currentPage)b=0-(onePageBook.bookLeft*2+onePageBook.bookWidth*1);a=el.id("canvas"+a);crossHTML5.transitionDuration(a,
onePageBook.flipSpeed+"ms");crossHTML5.transform(a)===""||crossHTML5.transform(a)==="translateX(0px)"||crossHTML5.transform(a)==="translate3d(0px, 0px, 0px)"?crossHTML5.transform(a,"translate3d("+b+"px, 0px,0px)","translateX("+b+"px)"):crossHTML5.transform(a,"translate3d(0px, 0px,0px)","translateX(0px)")},goToPage:function(a){if(a<0)a=1;else if(a>bookData.pageCount)a=bookData.pageCount;if(a==onePageBook.currentPage)pageMediator.change();else if(a==onePageBook.currentPage*1+1)onePageBook.next();else if(a==
onePageBook.currentPage*1-1)onePageBook.prev();else if(a>0&&a<=bookData.pageCount&&timer.check("fx")){if(a*1>onePageBook.currentPage*1)var b=onePageBook.currentPage*1+1,c=onePageBook.currentPage;else c=b=onePageBook.currentPage-1;var d=el.id("canvas"+b).getContext("2d");d.fillStyle="rgb(255,255,255)";d.fillRect(0,0,onePageBook.bookWidth,onePageBook.bookHeight);preloader.add(b);preloader.setSpecial(b);this.slideFxPage(c);this.currentPage=a;pager.change();var e=function(){onePageBook.destroy();onePageBook.draw(a);
window.scrollTo(0,1);delete e};d=null;window.setTimeout(e,onePageBook.flipSpeed);b=c=null}},destroyOtherPages:function(){for(var a=onePageBook.currentPage*1+onePageBook.nextPageBuffer*1,b=onePageBook.currentPage-onePageBook.prevPageBuffer;b<=a;b++)b!=onePageBook.currentPage&&b>0&&b<=bookData.pageCount&&el.del("canvas"+b)},goToZoom:function(){this.destroyOtherPages();var a=orientationObserver.getOrientation()=="portrait"?browser.publisher.name==="publisher"?screen.height/2/onePageBook.bookWidth:screen.height/
onePageBook.bookWidth:browser.publisher.name==="publisher"?screen.height/2/onePageBook.bookWidth:screen.height/onePageBook.bookWidth;if(device.name()!="iPad"||device.name!="other")a*=1.4;var b=el.id("canvas"+onePageBook.currentPage);if(b.style.left||b.style.left=="0px"){crossHTML5.transitionDuration(b,"0ms");crossHTML5.transform(b,"translate3d(0px, 0px,0px)","translate(0px, 0px)");b.style.left="0px"}window.setTimeout(function(){crossHTML5.transitionDuration(b,zoomBook.zoomIOSpeed+"ms");crossHTML5.transform(b,
"scale3d("+a+","+a+",1)","scale("+a+")")},1);var c=function(){onePageBook.installed=false;onePageBook.destroyPage(onePageBook.currentPage);el.del("bookPortrait");zoomBook.draw(onePageBook.currentPage,a);delete c};window.setTimeout(c,zoomBook.zoomIOSpeed+10)},destroy:function(){preloader.stopAll();el.del("bookPortrait");onePageBook.installed=false}};
onePageBook.events={tapCount:0,clickCount:0,doubleTapTime:250,doubleClickTime:250,leftAndRightArea:0.15,touchStart:function(a){a.target.tagName=="CANVAS"&&links.drawRect(a)},touchMove:function(a){if(links.isLinkBool){var b=a.targetTouches[0].pageY-eventManager.touchStartCoordinate.y;if(Math.abs(a.targetTouches[0].pageX-eventManager.touchStartCoordinate.x)>10||Math.abs(b)>10)links.clearRect()}delete a},touchEnd:function(a){if(!zoomBook.installed)if(eventManager.touchStartCoordinate.x-a.changedTouches[0].pageX<
-50)onePageBook.events.flipRight();else eventManager.touchStartCoordinate.x-a.changedTouches[0].pageX>50?onePageBook.events.flipLeft():onePageBook.events.touchManger(a)},touchManger:function(a){if(links.isLinkBool&&links.currURLs){links.clearRect();if(links.currURLs)for(var b=0;b<links.currURLs.length;b++)window.open(links.currURLs[b])}else{onePageBook.events.tapCount++;if(onePageBook.events.tapCount==1){var c=function(){if(onePageBook.events.tapCount==1){onePageBook.events.singleTap(a);onePageBook.events.tapCount=
0}delete c};window.setTimeout(c,onePageBook.events.doubleTapTime)}else{onePageBook.events.doubleTap(a);onePageBook.events.tapCount=0}}},mousedown:function(a){a.target.tagName=="CANVAS"&&links.drawRect(a);delete null},mouseup:function(a){if(!zoomBook.installed){var b=browser.publisher.name==="publisher"?a.pageX/1.3:a.pageX;if(eventManager.clickStartCoordinate.x-b<-50)onePageBook.events.flipRight();else eventManager.clickStartCoordinate.x-b>50?onePageBook.events.flipLeft():onePageBook.events.clickManger(a)}},
mousemove:function(a){if(links.isLinkBool){var b=a.pageY-eventManager.clickStartCoordinate.y;if(Math.abs(a.pageX-eventManager.clickStartCoordinate.x)>10||Math.abs(b)>10)links.clearRect()}delete a},clickManger:function(a){if(links.isLinkBool&&links.currURLs){links.clearRect();if(links.currURLs)for(var b=0;b<links.currURLs.length;b++)window.open(links.currURLs[b])}else{onePageBook.events.clickCount++;if(onePageBook.events.clickCount==1){var c=function(){if(onePageBook.events.clickCount==1){onePageBook.events.singleClick(a);
onePageBook.events.clickCount=0}delete c};window.setTimeout(c,onePageBook.events.doubleClickTime)}else{onePageBook.events.doubleClick(a);onePageBook.events.clickCount=0}}},singleTap:function(a){if(links.isLinkBool){links.clearRect();links.currGoPage&&onePageBook.goToPage(links.currGoPage)}else if(a.changedTouches[0].pageX<device.width()*onePageBook.events.leftAndRightArea)onePageBook.prev();else a.changedTouches[0].pageX>device.width()-device.width()*onePageBook.events.leftAndRightArea?onePageBook.next():
toolbar.toogle();delete a},doubleTap:function(){links.isLinkBool&&links.clearRect();onePageBook.goToZoom()},singleClick:function(a){if(links.isLinkBool){links.clearRect();links.currGoPage&&onePageBook.goToPage(links.currGoPage);if(links.currURLs)for(a=0;a<links.currURLs.length;a++)window.open(links.currURLs[a])}else{if(a.x<device.width()*onePageBook.events.leftAndRightArea)onePageBook.prev();else a.x>device.width()-device.width()*onePageBook.events.leftAndRightArea?onePageBook.next():toolbar.toogle();
delete a}},doubleClick:function(){links.isLinkBool&&links.clearRect();onePageBook.goToZoom()},flipLeft:function(){onePageBook.next()},flipRight:function(){onePageBook.prev()}};
var orientationObserver={start:function(){if(browser.platform.android){window.addEventListener("resize",workspace.reDraw,false);var a=function(){if(onePageBook.installed){onePageBook.destroy();onePageBook.draw(onePageBook.currentPage)}delete a};window.addEventListener("resize",a,false)}else{window.addEventListener("orientationchange",workspace.reDraw,false);a=function(){if(device.name()=="iPad")if(orientationObserver.getOrientation()=="portrait"){if(twoPageBook.installed){twoPageBook.destroy();onePageBook.draw(twoPageBook.currentPage.right)}}else{if(orientationObserver.getOrientation()==
"landscape")if(onePageBook.installed){onePageBook.destroy();twoPageBook.draw(onePageBook.currentPage)}}else if(onePageBook.installed){onePageBook.destroy();onePageBook.draw(onePageBook.currentPage)}delete a};window.addEventListener("orientationchange",a,false)}},stop:function(){browser.platform.android?window.removeEventListener("resize",workspace.reDraw,false):window.removeEventListener("orientationchange",workspace.reDraw,false)},getOrientation:function(){if(browser.platform.android){if(device.width()>
device.height())return"landscape";if(device.width()<device.height())return"portrait"}else{if(Math.abs(window.orientation)===0||Math.abs(window.orientation)===180)return"portrait";if(Math.abs(window.orientation)===90)return"landscape"}}},pageMediator={next:function(){if(slideShow.state=="unlock")if(onePageBook.installed&&!zoomBook.installed){onePageBook.next();toc.hide()}else if(twoPageBook.installed&&!zoomBook.installed)twoPageBook.next();else zoomBook.installed&&zoomBook.next()},prev:function(){if(slideShow.state==
"unlock")if(onePageBook.installed&&!zoomBook.installed){onePageBook.prev();toc.hide()}else if(twoPageBook.installed&&!zoomBook.installed)twoPageBook.prev();else zoomBook.installed&&zoomBook.prev()},change:function(){if(slideShow.state=="unlock"){pager.change();twoPageBook.installed&&twoPageBook.shadow.reDraw()}},last:function(){slideShow.state=="unlock"&&pageMediator.goToPage(bookData.pageCount)},first:function(){slideShow.state=="unlock"&&pageMediator.goToPage(1)},slideShow:function(){if(!zoomBook.installed){slideShow.toGo();
toolbar.keyStateCheck()}},slideNext:function(){if(onePageBook.installed&&!zoomBook.installed)onePageBook.next();else twoPageBook.installed&&!zoomBook.installed&&twoPageBook.next()},goToPage:function(a){if(onePageBook.installed&&!zoomBook.installed){onePageBook.goToPage(a);toc.tocLock==false&&toc.hide();toc.tocLock=false}else if(twoPageBook.installed&&!zoomBook.installed)twoPageBook.goToPage(a);else zoomBook.installed&&zoomBook.goToPage(a)}},pager={installed:false,state:"show",draw:function(){if(toolbar.installed){var a=
toolbar.toolbarHeight/100*40,b=(toolbar.toolbarHeight-(a+4))/2;if(!pager.installed){var c=el.add("span");c.style.cssFloat="left";c.style.margin=b+"px 0 0 "+b+"px";c.style.color="#e5e5e5";c.style.fontSize=a+"px";c.style.padding="0px";c.style.fontFamily="Helvetica Neue, HelveticaNeue, Helvetica-Neue, Helvetica, BBAlpha Sans, sans-serif";c.style.textShadow="rgba(0, 0, 0, 0.496094) 0px -0.08em 0px";var d=document.createTextNode("Page  ");c.appendChild(d);el.id("topToolbar").appendChild(c);d=el.add("span");
d.id="pagerCurrentPage";d.style.margin=b+"px 0 0 0";d.style.color="#e5e5e5";d.style.fontSize=a+"px";d.style.fontFamily="Helvetica Neue, HelveticaNeue, Helvetica-Neue, Helvetica, BBAlpha Sans, sans-serif";d.style.textShadow="rgba(0, 0, 0, 0.496094) 0px -0.08em 0px";d.innerHTML="0";c.appendChild(d);d=document.createTextNode(" of "+bookData.pageCount);c.appendChild(d)}pager.installed=true;eventManager.pagerEvent()}},change:function(){toolbar.keyStateCheck();window.scrollTo(0,1);pager.state=="input"&&
pager.cancelInput();if(onePageBook.installed&&!zoomBook.installed){var a=el.id("pagerCurrentPage");a.removeChild(a.childNodes[0]);nTe=document.createTextNode(onePageBook.currentPage);a.appendChild(nTe);window.location.hash="#"+onePageBook.currentPage}else if(twoPageBook.installed&&!zoomBook.installed)if(twoPageBook.currentPage.left>0&&twoPageBook.currentPage.right<=bookData.pageCount){a=el.id("pagerCurrentPage");a.removeChild(a.childNodes[0]);nTe=document.createTextNode(twoPageBook.currentPage.left+
"-"+twoPageBook.currentPage.right);a.appendChild(nTe);window.location.hash="#"+twoPageBook.currentPage.left}else if(twoPageBook.currentPage.left<=0){a=el.id("pagerCurrentPage");a.removeChild(a.childNodes[0]);nTe=document.createTextNode(twoPageBook.currentPage.right);a.appendChild(nTe);window.location.hash="#"+twoPageBook.currentPage.right}else{if(twoPageBook.currentPage.right>bookData.pageCount){a=el.id("pagerCurrentPage");a.removeChild(a.childNodes[0]);nTe=document.createTextNode(twoPageBook.currentPage.left);
a.appendChild(nTe);window.location.hash="#"+twoPageBook.currentPage.left}}else if(zoomBook.installed){a=el.id("pagerCurrentPage");a.removeChild(a.childNodes[0]);nTe=document.createTextNode(zoomBook.currentPage);a.appendChild(nTe);window.location.hash="#"+zoomBook.currentPage}},enableInput:function(a){a.target=a.target?a.target:a.srcElement;a.preventDefault();pager.state="input";var b=el.add("input");b.id="inputPage";b.type="number";b.style.height=toolbar.toolbarHeight/100*40+"px";b.style.width=toolbar.toolbarHeight/
100*120+"px";b.style.verticalAlign="text-top";b.style.padding="0px";b.style.border="1px solid white";b.style.textAlign="center";var c=el.id("pagerCurrentPage");c.parentNode.replaceChild(b,c);b.focus();eventManager.pagerInputEvent();a.preventDefault()},cancelInput:function(){var a=toolbar.toolbarHeight/100*40,b=(toolbar.toolbarHeight-(a+4))/2,c=el.add("span");c.id="pagerCurrentPage";c.style.margin=b+"px 0 0 0";c.style.color="#e5e5e5";c.style.fontSize=a+"px";if(onePageBook.installed)a=onePageBook.currentPage;
else if(twoPageBook.installed){a="";if(twoPageBook.currentPage.left>0&&twoPageBook.currentPage.left<=bookData.pageCount)a=a+twoPageBook.currentPage.left+"-";if(twoPageBook.currentPage.right>0&&twoPageBook.currentPage.right<=bookData.pageCount)a+=twoPageBook.currentPage.right}else a=zoomBook.installed?zoomBook.currentPage:"0";a=document.createTextNode(a);c.appendChild(a);c.addEventListener("click",pager.enableInput);a=el.id("inputPage");a.parentNode.replaceChild(c,a);pager.state="show"}},preloader=
{image:new Image,interval:null,preloadersStack:[],imageLoad:false,angle:0,special:0,init:function(){this.image.src=STYLES_SRC+"progress.png";this.image.onload=function(){preloader.imageLoad=true;if(preloader.preloadersStack.length>0){for(var a=0;a<preloader.preloadersStack.length;a++){var b=el.id("canvas"+preloader.preloadersStack[a]);preloader.draw(b);var c=b.getContext("2d");c.save();c.translate(b.width/2,b.height/2);c.drawImage(preloader.image,-20,-20,40,40);c.restore()}preloader.startInterval()}}},
add:function(a){if(el.id("canvas"+a)){preloader.imageLoad&&preloader.draw(el.id("canvas"+a),a);this.preloadersStack.push(a);preloader.preloadersStack.length==1&&preloader.imageLoad&&preloader.startInterval()}},setSpecial:function(a){preloader.special=a},draw:function(a){var b=a.getContext("2d");b.save();b.translate(a.width/2,a.height/2);b.drawImage(preloader.image,-20,-20,40,40);b.restore()},startInterval:function(){clearInterval(preloader.interval);var a=function(){preloader.preloadersStack.length==
0&&preloader.stopInterval();preloader.angle+=6;if(preloader.angle==360)preloader.angle=0;if(onePageBook.installed){var b={};b.l=onePageBook.currentPage;b.r=onePageBook.currentPage}else if(twoPageBook.installed){b={};b.l=twoPageBook.currentPage.left;b.r=twoPageBook.currentPage.right}else if(zoomBook.installed){b={};b.l=zoomBook.currentPage;b.r=zoomBook.currentPage}for(var c=0;c<preloader.preloadersStack.length;c++)if(preloader.preloadersStack[c]==b.l||preloader.preloadersStack[c]==b.r||preloader.preloadersStack[c]==
preloader.special){var d=el.id("canvas"+preloader.preloadersStack[c]),e=d.getContext("2d");e.save();e.translate(d.width/2,d.height/2);e.rotate(preloader.angle*(Math.PI/180));e.fillStyle="rgb(255,255,255)";e.fillRect(-30,-30,60,60);e.drawImage(preloader.image,-20,-20,40,40);e.restore()}delete a};preloader.interval=window.setInterval(a,45)},stopInterval:function(){clearInterval(preloader.interval)},deletePreloader:function(a){var b=preloader.preloadersStack.indexOf(a);if(el.id("canvas"+a)){a=el.id("canvas"+
a);var c=a.getContext("2d");c.save();c.translate(a.width/2,a.height/2);c.fillStyle="rgb(255,255,255)";c.fillRect(-30,-30,60,60);c.restore()}if(b!=-1){preloader.preloadersStack.splice(b,1);preloader.preloadersStack.length==0&&preloader.stopInterval()}},stopAll:function(){preloader.preloadersStack=[]}},slideShow={interval:null,state:"unlock",play:function(){slideShow.state="lock";slideShow.interval=window.setInterval(function(){if(onePageBook.installed)var a=onePageBook.currentPage;else if(twoPageBook.installed){a=
"";if(twoPageBook.currentPage.left>0&&twoPageBook.currentPage.left<=bookData.pageCount)a=a+twoPageBook.currentPage.left+"-";if(twoPageBook.currentPage.right>0&&twoPageBook.currentPage.right<=bookData.pageCount)a+=twoPageBook.currentPage.right;if(twoPageBook.currentPage.left==bookData.pageCount||twoPageBook.currentPage.right==bookData.pageCount)a=bookData.pageCount}else a="0";a==bookData.pageCount?pageMediator.goToPage(1):pageMediator.slideNext();pager.change()},2E3);toc&&toc.hide()},stop:function(){slideShow.state=
"unlock";clearInterval(slideShow.interval)},toGo:function(){if(slideShow.state=="lock")slideShow.stop();else slideShow.state=="unlock"&&slideShow.play()}};
timer={state:true,blockTime:0,endFX:0,startTime:Date.now(),setBlockTime:function(a,b){this.endFX=b||a;this.blockTime=a;this.startTime=Date.now()},check:function(a){a=a||"standart";if(a=="standart")return Date.now()-this.startTime>this.blockTime?true:false;else if(a=="high")return true;else if(a=="fx")return Date.now()-this.startTime>this.endFX?true:false}};
var toc={installed:false,state:"hide",mark:0,level:[],tocLock:false,shiftSpeed:800,parseLevel:function(a){var b;for(i=0;i<a;i++)b=i==0?bookData.TOC:b.tocElement[toc.level[i]].children;return b},init:function(){if(toolbar.installed)if(!toc.installed){toc.events.init();toc.tocButton.draw();toc.installed=true}},tocButton:{draw:function(){var a=el.add("span");a.style.cssFloat="left";a.id="tocButton";a.style.margin="4px 20px 0 13px";var b=el.add("img");b.id="imgTocButton";b.src=STYLES_SRC+"tocbutton.png";
b.style.height="32px";b.style.width="52px";b.style.cursor="pointer";a.appendChild(b);el.id("topToolbar").appendChild(a);toc.events.tocButton()},down:function(){el.id("imgTocButton").src=STYLES_SRC+"tocbuttononclick.png"},up:function(){el.id("imgTocButton").src=STYLES_SRC+"tocbutton.png"},action:function(){toc.state=="hide"?toc.display():toc.hide()}},backButton:{draw:function(){var a=el.add("div");a.id="backButton";a.style.position="absolute";a.style.left="10px";a.style.top="25px";var b=el.add("img");
b.id="imgBackButton";b.src=STYLES_SRC+"/backbuttoninactive.png";b.style.height="32px";b.style.width="52px";b.style.cursor="pointer";a.appendChild(b);el.id("tocContentBorder").appendChild(a);toc.events.backButton()},down:function(){if(toc.level.length<2)el.id("imgBackButton").src=STYLES_SRC+"backbuttoninactive.png";else el.id("imgBackButton").src=STYLES_SRC+"backbuttononclick.png"},check:function(){if(toc.level.length<2)el.id("imgBackButton").src=STYLES_SRC+"backbuttoninactive.png";else el.id("imgBackButton").src=
STYLES_SRC+"backbuttonactive.png"},action:function(){var a=toc.level.length;if(a>1){var b=toc.parseLevel(a-1);toc.content.leftShift();toc.mark=toc.level[a-1];toc.level=toc.level.slice(0,a-1);toc.content.generate(b);el.id("LI"+toc.mark).style.background="#888888";toc.backButton.check()}}},lable:{draw:function(){var a=el.add("div");a.style.position="absolute";a.style.left="65px";a.style.top="30px";a.style.height="20px";a.style.width="200px";a.id="tocContentLable";a.style.overflow="hidden";var b=el.add("h1");
b.align="center";b.style.color="#e5e5e5";b.style.fontSize="16px";var c=document.createTextNode("Table of Contents");b.appendChild(c);a.appendChild(b);el.id("tocContentBorder").appendChild(a)}},border:{width:344,draw:function(){toc.border.width=device.width()<344?device.width():344;var a=0.8*device.height(),b=el.add("div");b.style.position="absolute";b.style.left="2px";b.style.top="35px";b.style.height=a+"px";b.style.width=toc.border.width+"px";b.id="tocContentBorder";b.overflow="hidden";el.id("topToolbar").appendChild(b);
el.id("tocContentBorder").innerHTML='<div id="tocContentBorderBG1" style="border: 0px solid black; width: 54px; height: 68px; left: 0px; top: 0px; background: url(\''+STYLES_SRC+'tocborderimg/tocborder_01.png\'); position: absolute;"></div><div id="tocContentBorderBG2" style="border: 0px solid black; width: '+(toc.border.width-28-54)+"px; height: 68px; left: 54px; top: 0px; background: url('"+STYLES_SRC+'tocborderimg/tocborder_02.png\') repeat-x; position: absolute;"></div><div id="tocContentBorderBG3" style="border: 0px solid black; width: 28px; height: 68px; left: '+
(toc.border.width-28)+"px; top: 0px; background: url('"+STYLES_SRC+'tocborderimg/tocborder_04.png\'); position: absolute;"></div><div id="tocContentBorderBG4" style="border: 0px solid black; width: 10px; height: '+(a-68-33)+"px; left: 0px; top: 68px; background: url('"+STYLES_SRC+'tocborderimg/tocborder_05.png\') repeat-y; position: absolute;"></div><div id="tocContentBorderBG5" style="border: 0px solid black; width: 22px; height: '+(a-68-33)+"px; left: "+(toc.border.width-22)+"px; top: 68px; background: url('"+
STYLES_SRC+'tocborderimg/tocborder_07.png\') repeat-y; position: absolute;"></div><div id="tocContentBorderBG6" style="border: 0px solid black; width: 13px; height: 33px; left: 0px; top: '+(a-33)+"px; background: url('"+STYLES_SRC+'tocborderimg/tocborder_12.png\'); position: absolute;"></div><div id="tocContentBorderBG7" style="border: 0px solid black; width: '+(toc.border.width-13-24)+"px; height: 33px; left: 13px; top: "+(a-33)+"px; background: url('"+STYLES_SRC+'tocborderimg/tocborder_13.png\') repeat-x; position: absolute;"></div><div id="tocContentBorderBG8" style="border: 0px solid black; width: 24px; height: 33px; left: '+
(toc.border.width-24)+"px; top: "+(a-33)+"px; background: url('"+STYLES_SRC+'tocborderimg/tocborder_15.png\'); position: absolute;"></div><div id="tocContentBorderBG9" style="border: 0px solid black; width: '+(toc.border.width-10-22)+"px; height: "+(a-68-33)+'px; left: 10px; top: 68px; background: #e5e5e5; position: absolute;"></div>';b=el.add("div");b.style.position="absolute";b.style.left="6px";b.style.top="65px";b.style.height=a-95+"px";b.style.width=toc.border.width-24+"px";b.id="tocContent";
b.style.overflow="hidden";el.id("tocContentBorder").appendChild(b)}},content:{generate:function(a){var b=el.add("div");b.style.width=toc.border.width-24+"px";b.id="tocContentInner";b.style.position="absolute";el.id("tocContent").appendChild(b);toc.events.scroll();if(a){b=el.add("ul");b.id="UL";el.id("tocContentInner").appendChild(b);for(var c in a.tocElement){b=el.add("li");b.id="LI"+c;b.style.borderBottom="1px dotted #aaaaaa";b.style.padding="10px";b.style.listStyleType="none";b.style.cursor="pointer";
var d=document.createTextNode(a.tocElement[c].name);b.appendChild(d);if(a.tocElement[c].children){d=el.add("img");d.src=STYLES_SRC+"subtoc.png";d.align="right";b.appendChild(d)}el.id("UL").appendChild(b);toc.events.subToc("LI"+c)}}},remove:function(){el.del("tocContentInner")},draw:function(){var a=toc.parseLevel(toc.level.length);a&&toc.content.generate(a)},subToc:function(a){a=1*a.substring(2);var b=toc.level.length,c=toc.parseLevel(b);toc.tocLock=true;pageMediator.goToPage(c.tocElement[a].page);
if(c.tocElement[a].children){toc.content.rightShift();toc.level[b]=a;toc.content.generate(c.tocElement[toc.level[b]].children);toc.backButton.check()}},rightShift:function(){toc.content.remove()},leftShift:function(){toc.content.remove()}},display:function(){if(slideShow.state=="unlock"){toc.state="display";toc.border.draw();toc.lable.draw();toc.backButton.draw();toc.level[0]=0;toc.content.draw()}window.addEventListener("orientationchange",toc.hide,false)},hide:function(){if(toc.state=="display"){toc.state=
"hide";toc.level=[];el.del("tocContentBorder")}}};
toc.events={touchInterface:false,downCLk:false,moveCLk:false,startY:0,currY:0,deltaY:0,init:function(){toc.events.touchInterface="createTouch"in document?true:false},tocButton:function(){if(toc.events.touchInterface==false){el.id("tocButton").addEventListener("mouseup",toc.tocButton.action,false);el.id("tocButton").addEventListener("mousedown",toc.tocButton.down,false);el.id("tocButton").addEventListener("mouseup",toc.tocButton.up,false)}else{el.id("tocButton").addEventListener("touchend",toc.tocButton.action,
false);el.id("tocButton").addEventListener("touchstart",toc.tocButton.down,false);el.id("tocButton").addEventListener("touchend",toc.tocButton.up,false)}},backButton:function(){if(toc.events.touchInterface==false){el.id("backButton").addEventListener("mouseup",toc.backButton.action,false);el.id("backButton").addEventListener("mousedown",toc.backButton.down,false);el.id("backButton").addEventListener("mouseup",toc.backButton.check,false)}else{el.id("backButton").addEventListener("touchend",toc.backButton.action,
false);el.id("backButton").addEventListener("touchstart",toc.backButton.down,false);el.id("backButton").addEventListener("touchend",toc.backButton.check,false)}},subToc:function(a){if(toc.events.touchInterface==false){el.id(a).addEventListener("mousedown",toc.events.downSubToc,false);el.id(a).addEventListener("mouseup",toc.events.upSubToc,false)}else{el.id(a).addEventListener("touchstart",toc.events.downSubToc,false);el.id(a).addEventListener("touchend",toc.events.upSubToc,false)}},scroll:function(){if(toc.events.touchInterface==
false){el.id("tocContentInner").addEventListener("mousedown",toc.events.down,false);el.id("tocContentInner").addEventListener("mouseup",toc.events.up,false);el.id("tocContentInner").addEventListener("mousemove",toc.events.move,false)}else{el.id("tocContentInner").addEventListener("touchstart",toc.events.down,false);el.id("tocContentInner").addEventListener("touchend",toc.events.up,false);el.id("tocContentInner").addEventListener("touchcancel",toc.events.up,false);el.id("tocContentInner").addEventListener("touchmove",
toc.events.move,false)}},getId:function(a){return a.id?a.id:a.parentNode.id},downSubToc:function(a){a.preventDefault();a=toc.events.getId(a.target);a=a.substring(2);if(timer.check("fx"))el.id("LI"+a).style.background="#bbbbbb";if(a!=toc.mark&&toc.mark>0){el.id("LI"+toc.mark).style.background="";toc.mark=0}},upSubToc:function(a){a.preventDefault();a=toc.events.getId(a.target);el.id("LI"+a.substring(2)).style.background="";if(toc.events.deltaY==0&&timer.check("fx")){toc.content.subToc(a);toc.mark=0}},
down:function(a){a.preventDefault();toc.events.downClk=true;toc.events.startY=toc.events.touchInterface==false?a.pageY-el.id("tocContentInner").offsetTop:a.targetTouches[0].clientY-el.id("tocContentInner").offsetTop;toc.events.deltaY=0},up:function(a){a.preventDefault();toc.events.downClk=false},move:function(a){a.preventDefault();if(toc.events.downClk==true){a.preventDefault();var b=toc.events.getId(a.target);el.id("LI"+b.substring(2)).style.background="";toc.events.currY=toc.events.touchInterface==
false?a.pageY:a.targetTouches[0].clientY;toc.events.deltaY=toc.events.currY-toc.events.startY;a=el.id("tocContent").offsetHeight-el.id("tocContentInner").offsetHeight;if(toc.events.deltaY+el.id("tocContentInner").offsetTop>=0)el.id("tocContentInner").style.top="0px";else if(toc.events.deltaY>=a)el.id("tocContentInner").style.top=toc.events.deltaY+"px"}}};
var toolbar={toolbarHeight:40,status:"hide",installed:false,keyStateCheck:function(){if(onePageBook.installed)var a=onePageBook.currentPage;else if(twoPageBook.installed){a="";if(twoPageBook.currentPage.left>0&&twoPageBook.currentPage.left<=bookData.pageCount)a=a+twoPageBook.currentPage.left+"-";if(twoPageBook.currentPage.right>0&&twoPageBook.currentPage.right<=bookData.pageCount)a+=twoPageBook.currentPage.right;if(twoPageBook.currentPage.left==bookData.pageCount||twoPageBook.currentPage.right==bookData.pageCount)a=
bookData.pageCount}else a=zoomBook.installed?zoomBook.currentPage:"0";if(slideShow.state=="lock"){el.id("keyFirst").src=STYLES_SRC+"inactivefirst.png";el.id("keyPrev").src=STYLES_SRC+"inactiveprev.png";el.id("keyLast").src=STYLES_SRC+"inactivelast.png";el.id("keyNext").src=STYLES_SRC+"inactivenext.png"}else{if(a==1){el.id("keyFirst").src=STYLES_SRC+"inactivefirst.png";el.id("keyPrev").src=STYLES_SRC+"inactiveprev.png"}else{el.id("keyFirst").src=STYLES_SRC+"activefirst.png";el.id("keyPrev").src=STYLES_SRC+
"activeprev.png"}if(a==bookData.pageCount){el.id("keyLast").src=STYLES_SRC+"inactivelast.png";el.id("keyNext").src=STYLES_SRC+"inactivenext.png"}else{el.id("keyLast").src=STYLES_SRC+"activelast.png";el.id("keyNext").src=STYLES_SRC+"activenext.png"}}},draw:function(){if(!el.id("topToolbar")){var a=el.add("div");a.className="topToolbar";a.id="topToolbar";a.style.height=toolbar.toolbarHeight+"px";a.style.top="-"+toolbar.toolbarHeight-2+"px";el.id("body").appendChild(a)}if(!el.id("bottomToolbar")){a=
el.add("div");a.className="bottomToolbar";a.id="bottomToolbar";a.style.height=toolbar.toolbarHeight+"px";a.style.bottom="-"+toolbar.toolbarHeight-2+"px";var b=el.add("img");b.src=STYLES_SRC+"activelast.png";b.id="keyLast";b.style.height="20px";b.style.margin="10px 20px 0 0";b.style.cursor="pointer";b.style.cssFloat="right";b.addEventListener("click",pageMediator.last,false);a.appendChild(b);b=el.add("img");b.src=STYLES_SRC+"activenext.png";b.id="keyNext";b.style.height="20px";b.style.margin="10px 20px 0 0";
b.style.cursor="pointer";b.style.cssFloat="right";b.addEventListener("click",pageMediator.next,false);a.appendChild(b);b=el.add("img");b.src=STYLES_SRC+"slideshow.png";b.id="keySlideShow";b.style.height="20px";b.style.margin="10px 20px 0 0";b.style.cursor="pointer";b.style.cssFloat="right";b.addEventListener("click",pageMediator.slideShow,false);a.appendChild(b);b=el.add("img");b.src=STYLES_SRC+"inactiveprev.png";b.id="keyPrev";b.style.height="20px";b.style.margin="10px 20px 0 0";b.style.cursor="pointer";
b.style.cssFloat="right";b.addEventListener("click",pageMediator.prev,false);a.appendChild(b);b=el.add("img");b.src=STYLES_SRC+"inactivefirst.png";b.id="keyFirst";b.style.height="20px";b.style.margin="10px 20px 0 0";b.style.cursor="pointer";b.style.cssFloat="right";b.addEventListener("click",pageMediator.first,false);a.appendChild(b);el.id("body").appendChild(a)}toolbar.setToolbarHeight();toolbar.installed=true},setToolbarHeight:function(){toolbar.toolbarHeight=40},toogle:function(){pager.state==
"input"&&pager.cancelInput();if(this.status=="show"){var a=-toolbar.toolbarHeight-2;toolbar.status="hide";toc.hide()}else{a=toolbar.toolbarHeight+2;toolbar.status="show"}var b=el.id("topToolbar"),c=el.id("bottomToolbar");crossHTML5.transitionDuration(b,"0.3s");crossHTML5.transitionDuration(c,"0.3s");crossHTML5.transform(b,"translate3d(0px,"+a+"px,100px)","translateY("+a+"px) translateZ(100px)");crossHTML5.transform(c,"translate3d(0px,"+-a+"px,100px)","translateY("+-a+"px) translateZ(100px)")}},twoPageBook=
{currentPage:{left:0,right:0},installed:false,nextPageBuffer:2,prevPageBuffer:2,flipSpeed:800,triggerStopTime:850,bookWidth:0,bookHeight:0,bookTop:0,bookLeft:0,pageConverter:function(a){if(a%2!=0){twoPageBook.currentPage.left=a-1;twoPageBook.currentPage.right=a}else{twoPageBook.currentPage.left=a;twoPageBook.currentPage.right=a*1+1}twoPageBook.currentPage.left*=1;twoPageBook.currentPage.right*=1},draw:function(a){twoPageBook.pageConverter(a);if(bookData.size.proportions*2<device.proportions()){twoPageBook.bookWidth=
((device.height()-150)*bookData.size.proportions*2).toFixed(0);twoPageBook.bookHeight=(device.height()-150).toFixed(0)}else{twoPageBook.bookWidth=device.width()-150;twoPageBook.bookHeight=((device.width()-150)/(bookData.size.proportions*2)).toFixed(0)}twoPageBook.bookTop=((device.height()-twoPageBook.bookHeight)/2).toFixed(0);twoPageBook.bookLeft=((device.width()-twoPageBook.bookWidth)/2).toFixed(0);if(el.id("bookLandscape"))a=el.id("bookLandscape");else{a=el.add("div");a.id="bookLandscape";a.style.webkitPerspective=
"3000";a.style.position="absolute";a.style.width=twoPageBook.bookWidth+"px";a.style.height=twoPageBook.bookHeight+"px";a.style.top=twoPageBook.bookTop+"px";a.style.left=twoPageBook.bookLeft+"px";a.style.webkitBackfaceVisibility="hidden";el.id("mainFrame").appendChild(a)}twoPageBook.installed=true;for(var b=twoPageBook.currentPage.left*1;b>twoPageBook.currentPage.left-twoPageBook.prevPageBuffer*2;b-=2)twoPageBook.drawPage(b,a,"left");for(b=twoPageBook.currentPage.right*1;b<twoPageBook.currentPage.right*
1+twoPageBook.nextPageBuffer*2;b+=2)twoPageBook.drawPage(b,a,"right");pager.change();twoPageBook.shadow.draw();delete a},drawPage:function(a,b,c){if(c=="left")var d=a-1+"x"+a,e=a-1,h=device.name()=="android"?"rotateY(0deg)":"rotate3d(0, -1, 0, 0deg)",g=a;else if(c=="right"){d=a+"x"+(a*1+1);e=a*1+1;h=device.name()=="android"?"rotateY(0deg)":"rotate3d(0, 1, 0, 0deg)";g=bookData.pageCount-a}if(!el.id(d)){if(a>0&&a<=bookData.pageCount){var f=el.add("div");f.id=d;f.style.position="absolute";f.style.cssFloat=
c;if(c=="right")f.style.left=twoPageBook.bookWidth/2+"px";f.style.width=twoPageBook.bookWidth/2+"px";f.style.height=twoPageBook.bookHeight+"px";f.style.webkitTransformStyle="preserve-3d";f.style.webkitTransition="-webkit-transform 1s";f.style.webkitTransform=h;f.style.zIndex=g+"";b.appendChild(f);twoPageBook.drawCanvasPage(a,f,"front")}e>0&&e<=bookData.pageCount&&twoPageBook.drawCanvasPage(e,f,"back");delete b}},drawCanvasPage:function(a,b,c){var d=el.add("canvas");d.id="canvas"+a;d.className="canvasBook";
d.width=twoPageBook.bookWidth/2;d.height=twoPageBook.bookHeight;d.style.position="absolute";d.style.webkitBackfaceVisibility="hidden";d.style.webkitTransform=c=="front"?"":"rotateY(180deg)";d.style.zIndex=c=="front"?"1":"-1";c=d.getContext("2d");c.fillStyle="rgb(255,255,255)";c.fillRect(0,0,twoPageBook.bookWidth/2,twoPageBook.bookHeight);a==1||a==bookData.pageCount&&a%2==0||images.drawShadow(c,a);b.appendChild(d);if(!bookData.page[a].stub){images.push(a);preloader.add(a)}},next:function(){if(twoPageBook.installed&&
twoPageBook.currentPage.right<bookData.pageCount&&timer.check("fx")){twoPageBook.flipFxCurrentPage(twoPageBook.currentPage.right);if(el.id("bookLandscape").childNodes.length==4){var a=twoPageBook.currentPage.left*1-(twoPageBook.nextPageBuffer*2-1),b=twoPageBook.currentPage.right-(twoPageBook.nextPageBuffer*2-1);images.deleteImageFromStack(a);images.deleteImageFromStack(b);el.del(a+"x"+b);preloader.deletePreloader(a);preloader.deletePreloader(b)}twoPageBook.currentPage.left+=2;twoPageBook.currentPage.right+=
2;a=twoPageBook.currentPage.left*1+(twoPageBook.nextPageBuffer+1);el.id(a)||twoPageBook.drawPage(a,el.id("bookLandscape"),"right");pageMediator.change();timer.setBlockTime(twoPageBook.flipSpeed/2,twoPageBook.flipSpeed)}},prev:function(){if(twoPageBook.installed&&twoPageBook.currentPage.left>0&&timer.check("fx")){twoPageBook.flipFxCurrentPage(twoPageBook.currentPage.left);if(el.id("bookLandscape").childNodes.length==4){var a=twoPageBook.currentPage.left*1+(twoPageBook.prevPageBuffer*2-1),b=twoPageBook.currentPage.right*
1+(twoPageBook.prevPageBuffer*2-1);images.deleteImageFromStack(a);images.deleteImageFromStack(b);el.del(twoPageBook.currentPage.left*1+(twoPageBook.prevPageBuffer*2-1)+"x"+(twoPageBook.currentPage.right+(twoPageBook.prevPageBuffer*2-1)));preloader.deletePreloader(a);preloader.deletePreloader(b)}twoPageBook.currentPage.left-=2;twoPageBook.currentPage.right-=2;a=twoPageBook.currentPage.left*1-twoPageBook.prevPageBuffer;el.id(a)||twoPageBook.drawPage(a,el.id("bookLandscape"),"left");pageMediator.change();
timer.setBlockTime(twoPageBook.flipSpeed/2,twoPageBook.flipSpeed)}},goToPage:function(a){if(a<0)a=1;else if(a>bookData.pageCount)a=bookData.pageCount;if(a==twoPageBook.currentPage.left||a==twoPageBook.currentPage.right)pageMediator.change();else if(a==twoPageBook.currentPage.right*1+1||a==twoPageBook.currentPage.right*1+2)twoPageBook.next();else if(a==twoPageBook.currentPage.left*1-1||a==twoPageBook.currentPage.left*1-2)twoPageBook.prev();else if(a>0&&a<=bookData.pageCount&&timer.check("fx")){if(a>
twoPageBook.currentPage.right){if(a==bookData.pageCount&&a%2==0){for(var b=1,c=(twoPageBook.nextPageBuffer-1)*2;b<c;b+=2){var d=twoPageBook.currentPage.right*1+b*1+1+"x"+(twoPageBook.currentPage.right*1+b*1+2);el.del(d);d=null}c=el.id("canvas"+(twoPageBook.currentPage.right*1+1));c=c.getContext("2d");c.fillStyle="rgb(255,255,255)";c.fillRect(0,0,twoPageBook.bookWidth/2,twoPageBook.bookHeight);c=null;preloader.add(twoPageBook.currentPage.right*1+1);preloader.setSpecial(twoPageBook.currentPage.right*
1+1)}else for(b=1;b<=2;b++){c=el.id("canvas"+(twoPageBook.currentPage.right*1+b));c=c.getContext("2d");c.fillStyle="rgb(255,255,255)";c.fillRect(0,0,twoPageBook.bookWidth/2,twoPageBook.bookHeight);images.drawShadow(c,twoPageBook.currentPage.right*1+b);c=null;preloader.add(twoPageBook.currentPage.right*1+b);preloader.setSpecial(twoPageBook.currentPage.right*1+b)}twoPageBook.flipFxCurrentPage(twoPageBook.currentPage.right);twoPageBook.pageConverter(a);pageMediator.change()}else if(a<twoPageBook.currentPage.left){if(a==
1){b=1;for(c=(twoPageBook.prevPageBuffer-1)*2;b<c;b+=2){d=twoPageBook.currentPage.left*1-(b*1+2)+"x"+(twoPageBook.currentPage.left*1-(b*1+1));el.del(d);d=null}c=el.id("canvas"+(twoPageBook.currentPage.left*1-1));c=c.getContext("2d");c.fillStyle="rgb(255,255,255)";c.fillRect(0,0,twoPageBook.bookWidth/2,twoPageBook.bookHeight);preloader.add(twoPageBook.currentPage.left*1-1);preloader.setSpecial(twoPageBook.currentPage.left*1-1);c=c=null}else for(b=1;b<=2;b++){c=el.id("canvas"+(twoPageBook.currentPage.left-
b));c=c.getContext("2d");c.fillStyle="rgb(255,255,255)";c.fillRect(0,0,twoPageBook.bookWidth/2,twoPageBook.bookHeight);images.drawShadow(c,twoPageBook.currentPage.left-b);preloader.add(twoPageBook.currentPage.left-b);preloader.setSpecial(twoPageBook.currentPage.left-b);c=c=null}twoPageBook.flipFxCurrentPage(twoPageBook.currentPage.left);twoPageBook.pageConverter(a);pageMediator.change()}window.setTimeout(function(){preloader.stopAll();el.del("bookLandscape");twoPageBook.draw(a)},twoPageBook.flipSpeed+
100);timer.setBlockTime(twoPageBook.flipSpeed/2,twoPageBook.flipSpeed)}},flipFxCurrentPage:function(a){if(a%2!=0&&twoPageBook.installed&&twoPageBook.currentPage.right<bookData.pageCount){if(device.name()=="android"){var b=el.id(this.currentPage.right+"x"+(this.currentPage.right*1+1));if(b.style.webkitTransform=="rotateY(0deg)")var c=a==bookData.pageCount-1?"rotateY(-179."+(1E4-a)+"deg)":"rotateY(-179."+(1E4-a)+"deg)",d="0% 0%";else{c="rotateY(0deg)";d="100% 100%"}}else{b=el.id(this.currentPage.right+
"x"+(this.currentPage.right*1+1));if(b.style.webkitTransform=="rotate3d(0, 1, 0, 0deg)"||b.style.webkitTransform=="rotate3d(0, -1, 0, 0deg)"){c="rotate3d(0, -1, 0, 179."+(1E4-a)+"deg)";d="0% 0%"}else{c="rotate3d(0, -1, 0, 0deg)";d="100% 100%"}}var e=twoPageBook.currentPage.right*1+1}else if(twoPageBook.installed&&twoPageBook.currentPage.left>0){if(device.name()=="android"){b=el.id(this.currentPage.left-1+"x"+this.currentPage.left);if(b.style.webkitTransform=="rotateY(0deg)"){c=a==2||a==bookData.countPages?
"rotateY(179."+(1E4-(bookData.pageCount-a))+"deg)":"rotateY( 179."+(1E4-(bookData.pageCount-a))+"deg)";d="100% 100%"}else{c="rotateY(0deg)";d="0% 0%"}}else{b=el.id(this.currentPage.left-1+"x"+this.currentPage.left);if(b.style.webkitTransform=="rotate3d(0, -1, 0, 0deg)"||b.style.webkitTransform=="rotate3d(0, 1, 0, 0deg)"){c="rotate3d(0, 1, 0, 179."+(1E4-(bookData.pageCount-a))+"deg)";d="100% 100%"}else{c="rotate3d(0, 1, 0, 0deg)";d="0% 0%"}}e=bookData.pageCount-this.currentPage.left}b.style.webkitTransform=
c+"";b.style.webkitTransformOrigin=d+"";b.style.webkitTransitionTimingFunction="cubic-bezier(0, 0, 1, 0.95)";b.style.webkitTransitionDuration=this.flipSpeed+"ms";var h=function(){b.style.zIndex=e+"";for(var g=b.getElementsByTagName("*"),f=0;f<g.length;f++)g[f].style.zIndex=g[f].style.zIndex==="1"?"-1":"1";delete b;e=c=d=b=null;delete h};window.setTimeout(h,twoPageBook.flipSpeed/2);a=null},destroy:function(){preloader.stopAll();el.del("bookLandscape");twoPageBook.installed=false},goToZoom:function(a){var b=
a.target.id;if(b=="canvas"+twoPageBook.currentPage.left)var c=twoPageBook.currentPage.left,d=0,e=twoPageBook.bookWidth/4;else if(b=="canvas"+twoPageBook.currentPage.right){c=twoPageBook.currentPage.right;d=twoPageBook.bookWidth/2;e=-(twoPageBook.bookWidth/4)}var h=window.innerWidth/(twoPageBook.bookWidth/2),g=a.target;g.style.left=d+"px";el.id("bookLandscape").appendChild(g);if(g.style.webkitTransform=="rotateY(180deg)")g.style.webkitTransform="rotateY(0deg)";g.style.zIndex="500";var f=function(){g.style.webkitTransitionDuration=
zoomBook.zoomIOSpeed+"ms";g.style.webkitTransform=device.name()=="android"?"translate("+e+"px, 0px) scale("+h+","+h+")":"translate3d("+e+"px, 0px, 1px) scale3d("+h+","+h+",1)";delete f};window.setTimeout(f,1);var j=function(){twoPageBook.installed=false;twoPageBook.destroy();zoomBook.draw(c,h,twoPageBook.bookWidth/2,twoPageBook.bookHeight);b=c=d=e=null;delete j};window.setTimeout(j,zoomBook.zoomIOSpeed+10)}};
twoPageBook.shadow={shadowSize:3,draw:function(){if(twoPageBook.currentPage.right==1){if(el.id("3x4"))el.id("3x4").style.webkitBoxShadow="0px 0px "+this.shadowSize+"px #000"}else if(twoPageBook.currentPage.left==bookData.pageCount){var a=bookData.pageCount-3+"x"+(bookData.pageCount-2);if(el.id(a))el.id(a).style.webkitBoxShadow="0px 0px "+this.shadowSize+"px #000"}else if(el.id("bookLandscape"))el.id("bookLandscape").style.webkitBoxShadow="0px 0px "+this.shadowSize+"px #000"},erase:function(){if(el.id("3x4"))el.id("3x4").style.webkitBoxShadow=
"0px 0px 0px #000";var a=bookData.pageCount-3+"x"+(bookData.pageCount-2);if(el.id(a))el.id(a).style.webkitBoxShadow="0px 0px 0px #000";if(el.id("bookLandscape"))el.id("bookLandscape").style.webkitBoxShadow="0px 0px 0px #000"},reDraw:function(){if(twoPageBook.currentPage.left==2||twoPageBook.currentPage.left==bookData.pageCount-2)window.setTimeout(function(){twoPageBook.shadow.erase();twoPageBook.shadow.draw()},twoPageBook.flipSpeed);else if(twoPageBook.currentPage.right==1||twoPageBook.currentPage.left==
bookData.pageCount){this.erase();this.draw()}}};
twoPageBook.events={tapCount:0,clickCount:0,doubleTapTime:250,doubleClickTime:250,leftAndRightArea:0.15,touchStart:function(a){a.target.tagName=="CANVAS"&&links.drawRect(a);delete a},touchMove:function(a){if(links.isLinkBool){var b=a.targetTouches[0].pageY-eventManager.touchStartCoordinate.y;if(Math.abs(a.targetTouches[0].pageX-eventManager.touchStartCoordinate.x)>10||Math.abs(b)>10)links.clearRect()}delete a},touchEnd:function(a){if(eventManager.touchStartCoordinate.x-a.changedTouches[0].pageX<-50)twoPageBook.events.flipRight();
else eventManager.touchStartCoordinate.x-a.changedTouches[0].pageX>50?twoPageBook.events.flipLeft():twoPageBook.events.touchManger(a);delete a},mousedown:function(a){a.target.tagName=="CANVAS"&&links.drawRect(a);delete a},mousemove:function(a){if(links.isLinkBool){var b=a.pageY-eventManager.clickStartCoordinate.y;if(Math.abs(a.pageX-eventManager.clickStartCoordinate.x)>10||Math.abs(b)>10)links.clearRect()}delete a},mouseup:function(a){if(eventManager.clickStartCoordinate.x-a.pageX<-50)twoPageBook.events.flipRight();
else eventManager.clickStartCoordinate.x-a.pageX>50?twoPageBook.events.flipLeft():twoPageBook.events.clickManger(a);delete a},touchManger:function(a){if(links.isLinkBool&&links.currURLs){links.clearRect();if(links.currURLs)for(var b=0;b<links.currURLs.length;b++)window.open(links.currURLs[b])}else{twoPageBook.events.tapCount++;if(twoPageBook.events.tapCount==1){var c=function(){if(twoPageBook.events.tapCount==1){twoPageBook.events.singleTap(a);twoPageBook.events.tapCount=0}delete c};window.setTimeout(c,
twoPageBook.events.doubleTapTime)}else{twoPageBook.events.doubleTap(a);twoPageBook.events.tapCount=0}}},clickManger:function(a){if(links.isLinkBool&&links.currURLs){links.clearRect();if(links.currURLs)for(var b=0;b<links.currURLs.length;b++)window.open(links.currURLs[b])}else{twoPageBook.events.clickCount++;if(twoPageBook.events.clickCount==1){var c=function(){if(twoPageBook.events.clickCount==1){twoPageBook.events.singleClick(a);twoPageBook.events.clickCount=0}delete c};window.setTimeout(c,twoPageBook.events.doubleClickTime)}else{twoPageBook.events.doubleClick(a);
twoPageBook.events.clickCount=0}}},singleTap:function(a){if(links.isLinkBool){links.clearRect();links.currGoPage&&twoPageBook.goToPage(links.currGoPage)}else if(a.changedTouches[0].pageX<device.width()*twoPageBook.events.leftAndRightArea)twoPageBook.prev();else a.changedTouches[0].pageX>device.width()-device.width()*twoPageBook.events.leftAndRightArea?twoPageBook.next():toolbar.toogle();delete a},doubleTap:function(a){links.isLinkBool&&links.clearRect();a.target.tagName=="CANVAS"&&twoPageBook.goToZoom(a)},
singleClick:function(a){if(links.isLinkBool){links.clearRect();links.currGoPage&&twoPageBook.goToPage(links.currGoPage)}else{if(a.x<device.width()*twoPageBook.events.leftAndRightArea)twoPageBook.prev();else a.x>device.width()-device.width()*twoPageBook.events.leftAndRightArea?twoPageBook.next():toolbar.toogle();delete a;a=null}delete a},doubleClick:function(a){links.isLinkBool&&links.clearRect();a.target.tagName=="CANVAS"&&twoPageBook.goToZoom(a)},flipLeft:function(){twoPageBook.next()},flipRight:function(){twoPageBook.prev()}};
var workspace={draw:function(){var a=device.width()+"px",b=device.height()+"px";el.id("mainFrame").style.width=a;el.id("mainFrame").style.height=b;el.id("body").style.width=a;el.id("body").style.height=b},reDraw:function(){workspace.draw()}},zoomBook={currentPage:0,installed:false,verticalScroll:false,horizontalScroll:false,pageAreaWidth:0,pageAreaHeight:0,pageWidth:0,pageHeight:0,topShift:0,leftShift:0,innerShift:10,translateScrollX:0,translateScrollY:0,zoomFactor:0,currentPage:0,nextPageBuffer:1,
prevPageBuffer:1,slideSpeed:800,zoomIOSpeed:800,sourcePageHeight:0,sourcePageWidth:0,initSizes:function(a,b,c,d){this.zoomFactor=a;this.currentPage=d;this.pageWidth=b;this.pageHeight=c;this.pageAreaWidth=b>device.width()?b+this.innerShift:device.width();this.pageAreaHeight=c>device.height()?c:device.height();this.pageAreaWidth=this.pageAreaWidth;this.translateScrollY=((this.pageAreaHeight-device.height())/2).toFixed(0);this.translateScrollX=((this.pageAreaWidth-device.width())/2).toFixed(0);this.topShift=
((device.height()-c)/2).toFixed(0);this.leftShift=((device.width()-b)/2).toFixed(0);if(b.toFixed(0)>=device.width()){this.horizontalScroll=true;this.leftShift=0}else{this.horizontalScroll=false;this.translateScrollX=0}if(c.toFixed(0)>device.height()){this.verticalScroll=true;this.topShift=0}else{this.verticalScroll=false;this.translateScrollY=0}this.translateX=this.pageAreaWidth*(this.currentPage-1)+this.translateScrollX*1},draw:function(a,b,c,d){el.id("keySlideShow").src=STYLES_SRC+"inactiveslideshow.png";
b=b||this.zoomFactor;if(bookData.size.proportions<device.proportions()){onePageBook.bookHeight=(device.height()-50).toFixed(0);onePageBook.bookWidth=(onePageBook.bookHeight*bookData.size.proportions).toFixed(0)}else{onePageBook.bookWidth=device.width()-50;onePageBook.bookHeight=(onePageBook.bookWidth/bookData.size.proportions).toFixed(0)}this.sourcePageWidth=c||onePageBook.bookWidth;this.sourcePageHeight=d||onePageBook.bookHeight;pageWidth=this.sourcePageWidth*b;pageHeight=this.sourcePageHeight*b;
this.initSizes(b,pageWidth,pageHeight,a);if(!el.id("zoomBook")){b=el.add("div");b.id="zoomBook";crossHTML5.perspective(b,"3000");b.style.position="absolute";b.style.width=this.pageAreaWidth+"px";b.style.height=this.pageAreaHeight+"px";crossHTML5.backfaceVisibility(b,"hidden");crossHTML5.transform(b,"translate3d("+(-(this.translateScrollX*1)+this.innerShift/2)+"px,"+-this.translateScrollY+"px,0px)","translate("+-(this.translateScrollX*1)+"px,"+-this.translateScrollY+"px)");el.id("mainFrame").appendChild(b)}zoomBook.installed=
true;pager.change();for(b=a-zoomBook.prevPageBuffer;b<=a*1+zoomBook.nextPageBuffer;b++)zoomBook.drawPage(b)},drawPage:function(a){if(a>0&&a<=bookData.pageCount){var b=el.add("canvas");b.id="canvas"+a;b.className="canvasZoom";b.width=zoomBook.pageWidth;b.height=zoomBook.pageHeight;b.style.left=zoomBook.leftShift+"px";b.style.position="absolute";crossHTML5.backfaceVisibility(b,"hidden");var c=(a-zoomBook.currentPage)*zoomBook.pageAreaWidth;crossHTML5.transform(b,"translate3d("+c+"px, 0px, 0px)","translate("+
c+"px, 0px)");crossHTML5.boxShadow(b,"0px 0px 3px #000");c=b.getContext("2d");c.fillStyle="rgb(255,255,255)";c.fillRect(0,0,zoomBook.pageWidth,zoomBook.pageHeight);el.id("zoomBook").appendChild(b);if(!bookData.page[a].stub){images.push(a);preloader.add(a)}}},moveFX:function(a){for(var b=zoomBook.currentPage*1-zoomBook.prevPageBuffer;b<=zoomBook.currentPage*1+zoomBook.nextPageBuffer;b++)if(b>0&&b<=bookData.pageCount){if(el.id("canvas"+b)){var c=el.id("canvas"+b),d=(b-zoomBook.currentPage-a*1)*zoomBook.pageAreaWidth;
crossHTML5.transitionDuration(c,zoomBook.slideSpeed+"ms");crossHTML5.transform(c,"translate3d("+d+"px, 0px, 0px)","translate("+d+"px, 0px)")}this.adjustmentFX()}},adjustmentFX:function(){this.translateScrollX=this.translateScrollY=0;var a=el.id("zoomBook");crossHTML5.transitionDuration(a,zoomBook.slideSpeed+"ms");crossHTML5.transform(a,"translate3d("+-this.translateScrollX+"px,"+-this.translateScrollY+"px,0px)","translate("+-this.translateScrollX+"px,"+-this.translateScrollY+"px)")},next:function(){if(zoomBook.currentPage<
bookData.pageCount&&timer.check("fx")){zoomBook.moveFX(1);zoomBook.currentPage++;pager.change();var a=function(){var b=zoomBook.currentPage-zoomBook.prevPageBuffer-1;el.id("canvas"+b)&&el.del("canvas"+b);images.deleteImageFromStack(b);preloader.deletePreloader(b);delete a;zoomBook.drawPage(zoomBook.currentPage*1+zoomBook.nextPageBuffer)};window.setTimeout(a,zoomBook.slideSpeed);timer.setBlockTime(zoomBook.slideSpeed/2,zoomBook.slideSpeed)}},prev:function(){if(zoomBook.currentPage>1&&timer.check("fx")){zoomBook.moveFX(-1);
zoomBook.currentPage--;pager.change();var a=function(){var b=zoomBook.currentPage*1+zoomBook.nextPageBuffer*1+1;el.id("canvas"+b)&&el.del("canvas"+b);images.deleteImageFromStack(b);preloader.deletePreloader(b);delete a;zoomBook.drawPage(zoomBook.currentPage*1-zoomBook.prevPageBuffer)};window.setTimeout(a,zoomBook.slideSpeed);timer.setBlockTime(zoomBook.slideSpeed/2,zoomBook.slideSpeed)}},destroy:function(){preloader.stopAll();el.del("zoomBook")},goToPage:function(a){if(a<0)a=1;else if(a>bookData.pageCount)a=
bookData.pageCount;if(a==zoomBook.currentPage)pageMediator.change();else if(a==zoomBook.currentPage*1+1)zoomBook.next();else if(a==zoomBook.currentPage*1-1)zoomBook.prev();else if(a>0&&a<=bookData.pageCount&&timer.check("fx")){if(a*1>zoomBook.currentPage*1){var b=zoomBook.currentPage*1+1,c=el.id("canvas"+b).getContext("2d");b=null;c.fillStyle="rgb(255,255,255)";c.fillRect(0,0,zoomBook.pageWidth,zoomBook.pageHeight);preloader.add(zoomBook.currentPage*1+1);preloader.setSpecial(zoomBook.currentPage*
1+1);zoomBook.moveFX(1)}else{b=zoomBook.currentPage*1-1;c=el.id("canvas"+b).getContext("2d");b=null;c.fillStyle="rgb(255,255,255)";c.fillRect(0,0,zoomBook.pageWidth,zoomBook.pageHeight);preloader.add(zoomBook.currentPage*1-1);preloader.setSpecial(zoomBook.currentPage*1-1);zoomBook.moveFX(-1)}zoomBook.currentPage=a;pager.change();var d=function(){zoomBook.destroy();zoomBook.draw(a,zoomBook.zoomFactor,zoomBook.sourcePageWidth,zoomBook.sourcePageHeight);zoomBook.adjustmentFX();delete d};c=null;window.setTimeout(d,
zoomBook.slideSpeed)}},scroll:function(a,b){if(this.horizontalScroll)if(this.translateScrollX-a>this.pageWidth-device.width()){var c=this.pageWidth-device.width()-this.translateScrollX;a=-(c-(a+c)/2)}else{if(this.translateScrollX-a<0)a=this.translateScrollX*1-(this.translateScrollX*1-a)/3}else a=0;if(this.verticalScroll)if(this.translateScrollY-b>this.pageHeight-device.height()){c=this.pageHeight-device.height()-this.translateScrollY;b=-(c-(b+c)/2)}else{if(this.translateScrollY-b<0)b=this.translateScrollY*
1-(this.translateScrollY*1-b)/3}else b=0;c=el.id("zoomBook");crossHTML5.transitionDuration(c,"0ms");crossHTML5.transform(c,"translate3d("+(-this.translateScrollX*1+a*1)+"px,"+(-this.translateScrollY*1+b*1)+"px,0px)","translate("+(-this.translateScrollX*1+a*1)+"px,"+(-this.translateScrollY*1+b*1)+"px)")},scrollEnd:function(a,b){var c=this.horizontalScroll?device.name()=="iPad"?-300:-125:device.name()=="iPad"?-130:-50;if(this.translateScrollX-a>this.pageWidth-device.width()&&a<c&&this.currentPage!=
bookData.pageCount)this.next();else if(this.translateScrollX-a<0&&this.currentPage!=1&&this.translateScrollX*1-a<c)this.prev();else{if(this.verticalScroll)if(this.translateScrollY-b>this.pageHeight-device.height())this.translateScrollY=this.pageHeight-device.height();else if(this.translateScrollY-b<0)this.translateScrollY=0;else this.translateScrollY-=b;if(this.horizontalScroll)if(this.translateScrollX-a>this.pageWidth-device.width())this.translateScrollX=this.pageWidth-device.width();else if(this.translateScrollX-
a<0)this.translateScrollX=0;else this.translateScrollX-=a;c=el.id("zoomBook");crossHTML5.transitionDuration(c,"300ms");crossHTML5.transform(c,"translate3d("+-this.translateScrollX+"px,"+-this.translateScrollY+"px,0px)","translate("+-this.translateScrollX+"px,"+-this.translateScrollY+"px)")}maxDeltaX=null},zoomOutOnePage:function(){if(bookData.size.proportions<device.proportions()){onePageBook.bookHeight=(device.height()-50).toFixed(0);onePageBook.bookWidth=(onePageBook.bookHeight*bookData.size.proportions).toFixed(0)}else{onePageBook.bookWidth=
device.width()-50;onePageBook.bookHeight=(onePageBook.bookWidth/bookData.size.proportions).toFixed(0)}var a=onePageBook.bookWidth/zoomBook.pageWidth,b=zoomBook.verticalScroll?(zoomBook.pageHeight-device.height())/2:0,c=zoomBook.horizontalScroll?(zoomBook.pageWidth-device.width())/2:0;zoomEl=el.id("canvas"+zoomBook.currentPage);crossHTML5.transitionDuration(el.id("zoomBook"),"150ms");crossHTML5.transform(el.id("zoomBook"),"translate3d("+-c+"px,"+-b+"px,0px)","translate("+-c+"px,"+-b+"px)");crossHTML5.transitionDuration(zoomEl,
zoomBook.zoomIOSpeed+"ms");crossHTML5.transform(zoomEl,"scale3d("+a+","+a+",1)","scale("+a+")");var d=function(){zoomBook.destroy();zoomBook.installed=false;onePageBook.draw(zoomBook.currentPage);delete d};b=c=a=null;window.setTimeout(d,zoomBook.zoomIOSpeed+50)},zoomOutTwoPage:function(){if(bookData.size.proportions*2<device.proportions()){twoPageBook.bookWidth=((device.height()-150)*bookData.size.proportions*2).toFixed(0);twoPageBook.bookHeight=(device.height()-150).toFixed(0)}else{twoPageBook.bookWidth=
device.width()-150;twoPageBook.bookHeight=((device.width()-150)/(bookData.size.proportions*2)).toFixed(0)}var a=twoPageBook.bookWidth/2/zoomBook.pageWidth,b=zoomBook.verticalScroll?(zoomBook.pageHeight-device.height())/2:0,c=zoomBook.horizontalScroll?(zoomBook.pageWidth-device.width())/2:0;if(zoomBook.currentPage%2==0)c+=twoPageBook.bookWidth/4;else c-=twoPageBook.bookWidth/4;zoomEl=el.id("canvas"+zoomBook.currentPage);zoomBook.destroyOtherPages();crossHTML5.transitionDuration(el.id("zoomBook"),"150ms");
crossHTML5.transform(el.id("zoomBook"),"translate3d("+-c+"px,"+-b+"px,0px)","translate("+-c+"px,"+-b+"px)");crossHTML5.transitionDuration(zoomEl,zoomBook.zoomIOSpeed+"ms");crossHTML5.transform(zoomEl,"scale3d("+a+","+a+",1)","scale("+a+")");var d=function(){zoomBook.destroy();zoomBook.installed=false;twoPageBook.draw(zoomBook.currentPage);delete d};window.setTimeout(d,zoomBook.zoomIOSpeed+50);b=c=a=null},zoomOut:function(a){el.id("keySlideShow").src=STYLES_SRC+"slideshow.png";bookChoice.getType()===
"one"?zoomBook.zoomOutOnePage(a):zoomBook.zoomOutTwoPage(a)},destroyOtherPages:function(){for(var a=zoomBook.currentPage*1+zoomBook.nextPageBuffer*1,b=zoomBook.currentPage-zoomBook.prevPageBuffer;b<=a;b++)b!=zoomBook.currentPage&&b>0&&b<=bookData.pageCount&&el.del("canvas"+b)}};
zoomBook.events={tapCount:0,clickCount:0,doubleTapTime:250,doubleClickTime:250,leftAndRightArea:0.15,touchStart:function(a){a.target.tagName=="CANVAS"&&links.drawRect(a);delete a},touchMove:function(a){var b=a.targetTouches[0].pageX-eventManager.touchStartCoordinate.x,c=a.targetTouches[0].pageY-eventManager.touchStartCoordinate.y;if(links.isLinkBool&&(Math.abs(b)>2||Math.abs(c)>2))links.clearRect();zoomBook.scroll(b,c);delete a},touchEnd:function(a){Math.abs(eventManager.touchStartCoordinate.x-a.changedTouches[0].pageX)>
2||Math.abs(eventManager.touchStartCoordinate.y-a.changedTouches[0].pageY)>2?zoomBook.scrollEnd(a.changedTouches[0].pageX-eventManager.touchStartCoordinate.x,a.changedTouches[0].pageY-eventManager.touchStartCoordinate.y):zoomBook.events.touchManger(a)},mousedown:function(a){a.target.tagName=="CANVAS"&&links.drawRect(a);delete a},mousemove:function(a){var b=a.pageX-eventManager.clickStartCoordinate.x,c=a.pageY-eventManager.clickStartCoordinate.y;if(links.isLinkBool&&(Math.abs(b)>2||Math.abs(c)>2))links.clearRect();
zoomBook.scroll(b,c);delete a},mouseup:function(a){Math.abs(eventManager.clickStartCoordinate.x-a.pageX)>2||Math.abs(eventManager.clickStartCoordinate.y-a.pageY)>2?zoomBook.scrollEnd(a.pageX-eventManager.clickStartCoordinate.x,a.pageY-eventManager.clickStartCoordinate.y):zoomBook.events.clickManger(a)},touchManger:function(a){if(links.isLinkBool&&links.currURLs){links.clearRect();if(links.currURLs){for(var b=0;b<links.currURLs.length;b++)window.open(links.currURLs[b]);b=null}}else{zoomBook.events.tapCount++;
if(zoomBook.events.tapCount==1){var c=function(){if(zoomBook.events.tapCount==1){zoomBook.events.singleTap(a);zoomBook.events.tapCount=0}delete c};window.setTimeout(c,zoomBook.events.doubleTapTime)}else{zoomBook.events.doubleTap(a);zoomBook.events.tapCount=0}}},clickManger:function(a){if(links.isLinkBool&&links.currURLs){links.clearRect();if(links.currURLs)for(var b=0;b<links.currURLs.length;b++)window.open(links.currURLs[b])}else{zoomBook.events.clickCount++;if(zoomBook.events.clickCount==1){var c=
function(){if(zoomBook.events.clickCount==1){zoomBook.events.singleClick(a);zoomBook.events.clickCount=0}delete c};window.setTimeout(c,zoomBook.events.doubleClickTime)}else{zoomBook.events.doubleClick(a);zoomBook.events.clickCount=0}}},singleTap:function(a){if(links.isLinkBool){links.clearRect();links.currGoPage&&zoomBook.goToPage(links.currGoPage)}else if(a.changedTouches[0].pageX<device.width()*zoomBook.events.leftAndRightArea)zoomBook.prev();else a.changedTouches[0].pageX>device.width()-device.width()*
zoomBook.events.leftAndRightArea?zoomBook.next():toolbar.toogle();delete a},doubleTap:function(){links.isLinkBool&&links.clearRect();zoomBook.zoomOut()},singleClick:function(a){if(links.isLinkBool){links.clearRect();links.currGoPage&&zoomBook.goToPage(links.currGoPage)}else{var b=browser.publisher.name==="publisher"?device.width()/2:device.width();if(a.x<b*twoPageBook.events.leftAndRightArea)zoomBook.prev();else a.x>b-b*twoPageBook.events.leftAndRightArea?zoomBook.next():toolbar.toogle()}delete a},
doubleClick:function(a){links.isLinkBool&&links.clearRect();zoomBook.zoomOut(a)},flipLeft:function(){zoomBook.next()},flipRight:function(){zoomBook.prev()}};
